pipeline:
  tests:
    image: node:7-alpine
    when:
      event: push
    commands:
      - yarn
      - yarn test
      - yarn run lint
      - yarn run build

  docker:
    image: plugins/docker
    when:
      branch:
        - prod
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego-webapp
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
