pipeline:
  tests:
    image: node:7-alpine
    when:
      event: push
    commands:
      - yarn
      - yarn test
      - yarn run lint
      - yarn run build
  docker:
    image: plugins/docker
    when:
      branch:
        - prod
      event: push
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego-webapp
    secrets: [ docker_username, docker_password ]
    tags:
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - RELEASE=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
      - SENTRY_AUTH_KEY='c3ec0fc29e2a49d3bf8f3f18aec98428537659db97334739b8283b3c1bb38603'
