FROM node:7-alpine

MAINTAINER Abakus Webkom <webkom@abakus.no>

RUN mkdir /app
WORKDIR /app
COPY . /app

RUN yarn

ARG API_URL
ARG WS_URL
ARG BASE_URL
ARG CAPTCHA_KEY
ARG STRIPE_KEY
ARG RAVEN_DSN
ARG RELEASE

ENV NODE_ENV production
ENV API_URL ${API_URL}
ENV WS_URL ${WS_URL}
ENV BASE_URL ${BASE_URL}
ENV CAPTCHA_KEY ${CAPTCHA_KEY}
ENV STRIPE_KEY ${STRIPE_KEY}
ENV RAVEN_DSN ${RAVEN_DSN}
ENV RELEASE ${RELEASE}

RUN yarn run build

ENTRYPOINT ["node", "dist/server.js"]
