packages:
  - 'lego-webapp'
  - 'packages/**'

catalog:
  "@types/react": ^18.3.18
  "@types/react-dom": ^18.3.5
  classnames: ^2.5.1
  eslint: ^9.33.0
  lucide-react: ^0.483.0
  postcss-custom-media: ^11.0.5
  postcss-nested: ^7.0.2
  react-aria-components: ^1.7.1
  react-dom: ^18.3.1
  react: ^18.3.1
  typescript: ^5.6.3
  vite: ^6.2.5
  vitest: ^3.0.9
