packages:
  - 'lego-webapp'
  - 'packages/**'

catalog:
  "@types/react": ^19.3.0
  "@types/react-dom": ^19.3.0
  classnames: ^2.5.1
  eslint: ^9.39.5
  lucide-react: ^0.483.0
  postcss-custom-media: ^11.0.5
  postcss-nested: ^7.0.2
  react-aria-components: ^1.7.1
  react-dom: ^19.3.0
  react: ^19.3.0
  typescript: ^5.6.3
  vite: ^6.4.3
  vitest: ^3.2.7
