/**
 *
 */
export const Event = {
  FETCH: 'Event.FETCH',
  FETCH_BEGIN: 'Event.FETCH_BEGIN',
  FETCH_SUCCESS: 'Event.FETCH_SUCCESS',
  FETCH_FAILURE: 'Event.FETCH_FAILURE',
  FETCH_ALL: 'Event.FETCH_ALL',
  FETCH_ALL_BEGIN: 'Event.FETCH_ALL_BEGIN',
  FETCH_ALL_SUCCESS: 'Event.FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'Event.FETCH_ALL_FAILURE'
};

export const Group = {
  FETCH: 'Group.FETCH',
  FETCH_BEGIN: 'Group.FETCH_BEGIN',
  FETCH_SUCCESS: 'Group.FETCH_SUCCESS',
  FETCH_FAILURE: 'Group.FETCH_FAILURE',
  FETCH_ALL: 'Group.FETCH_ALL',
  FETCH_ALL_BEGIN: 'Group.FETCH_ALL_BEGIN',
  FETCH_ALL_SUCCESS: 'Group.FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'Group.FETCH_ALL_FAILURE'
};

/**
 *
 */
export const Favorite = {
  FETCH_ALL_SUCCESS: 'Favorite.FETCH_ALL_SUCCESS'
};

/**
 *
 */
export const Search = {
  SEARCH: 'Search.SEARCH',
  SEARCH_BEGIN: 'Search.SEARCH_BEGIN',
  SEARCH_FAILURE: 'Search.SEARCH_FAILURE',
  SEARCH_SUCCESS: 'Search.SEARCH_SUCCESS',
  RESULTS_RECEIVED: 'Search.RESULTS_RECEIVED'
};

/**
 *
 */
export const User = {
  FETCH: 'User.FETCH',
  FETCH_BEGIN: 'User.FETCH_BEGIN',
  FETCH_SUCCESS: 'User.FETCH_SUCCESS',
  FETCH_FAILURE: 'User.FETCH_FAILURE',
  UPDATE: 'User.UPDATE',
  UPDATE_BEGIN: 'User.UPDATE_BEGIN',
  UPDATE_SUCCESS: 'User.UPDATE_SUCCESS',
  UPDATE_FAILURE: 'User.UPDATE_FAILURE',
  LOGIN: 'User.LOGIN',
  LOGIN_BEGIN: 'User.LOGIN_BEGIN',
  LOGIN_SUCCESS: 'User.LOGIN_SUCCESS',
  LOGIN_FAILURE: 'User.LOGIN_FAILURE',
  LOGOUT: 'User.LOGOUT'
};
