/**
 *
 */
export const Events = {
  FETCH_EVENT: 'FETCH_EVENT',
  FETCH_EVENT_BEGIN: 'FETCH_EVENT_BEGIN',
  FETCH_EVENT_SUCCESS: 'FETCH_EVENT_SUCCESS',
  FETCH_EVENT_FAILURE: 'FETCH_EVENT_FAILURE',
  FETCH_ALL: 'FETCH_ALL',
  FETCH_ALL_BEGIN: 'FETCH_ALL_BEGIN',
  FETCH_ALL_SUCCESS: 'FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'FETCH_ALL_FAILURE'
};

/**
 *
 */
export const Favorites = {
  FETCH_ALL_SUCCESS: 'LOAD_ALL_SUCCESS'
};

/**
 *
 */
export const UI = {
  TOGGLE_MENU: 'TOGGLE_MENU',
  OPEN_MENU: 'OPEN_MENU',
  CLOSE_MENU: 'CLOSE_MENU',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN'
};

/**
 *
 */
export const Search = {
  CLEAR: 'CLOSE',
  SEARCH: 'SEARCH'
};

export const User = {
  FETCH_USER: 'FETCH_USER',
  FETCH_USER_BEGIN: 'FETCH_USER_BEGIN',
  FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
  FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',
  UPDATE_USER: 'UPDATE_USER',
  UPDATE_USER_BEGIN: 'UPDATE_USER_BEGIN',
  UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
  UPDATE_USER_FAILURE: 'UPDATE_USER_FAILURE',
  LOGIN: 'LOGIN',
  LOGIN_BEGIN: 'LOGIN_BEGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT'
};
