/**
 *
 */
export const Event = {
  FETCH: 'Event.FETCH',
  FETCH_BEGIN: 'Event.FETCH_BEGIN',
  FETCH_SUCCESS: 'Event.FETCH_SUCCESS',
  FETCH_FAILURE: 'Event.FETCH_FAILURE',
  FETCH_ALL: 'Event.FETCH_ALL',
  FETCH_ALL_BEGIN: 'Event.FETCH_ALL_BEGIN',
  FETCH_ALL_SUCCESS: 'Event.FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'Event.FETCH_ALL_FAILURE'
};

export const Group = {
  FETCH: 'Group.FETCH',
  FETCH_BEGIN: 'Group.FETCH_BEGIN',
  FETCH_SUCCESS: 'Group.FETCH_SUCCESS',
  FETCH_FAILURE: 'Group.FETCH_FAILURE',
  FETCH_ALL: 'Group.FETCH_ALL',
  FETCH_ALL_BEGIN: 'Group.FETCH_ALL_BEGIN',
  FETCH_ALL_SUCCESS: 'Group.FETCH_ALL_SUCCESS',
  FETCH_ALL_FAILURE: 'Group.FETCH_ALL_FAILURE',
  UPDATE: 'Group.UPDATE',
  UPDATE_BEGIN: 'Group.UPDATE_BEGIN',
  UPDATE_SUCCESS: 'Group.UPDATE_SUCCESS',
  UPDATE_FAILURE: 'Group.UPDATE_FAILURE'
};

/**
 *
 */
export const Favorite = {
  FETCH_ALL_SUCCESS: 'Favorite.FETCH_ALL_SUCCESS'
}

/**
 *
 */
export const Quotes = {
  FETCH_ALL_APPROVED: 'FETCH_ALL_APPROVED_QUOTES',
  FETCH_ALL_APPROVED_BEGIN: 'FETCH_ALL_APPROVED_QUOTES_BEGIN',
  FETCH_ALL_APPROVED_SUCCESS: 'FETCH_ALL_APPROVED_QUOTES_SUCCESS',
  FETCH_ALL_APPROVED_FAILURE: 'FETCH_ALL_APPROVED_QUOTES_FAILURE',
  FETCH_ALL_UNAPPROVED: 'FETCH_ALL_UNAPPROVED_QUOTES',
  FETCH_ALL_UNAPPROVED_BEGIN: 'FETCH_ALL_UNAPPROVED_QUOTES_BEGIN',
  FETCH_ALL_UNAPPROVED_SUCCESS: 'FETCH_ALL_UNAPPROVED_QUOTES_SUCCESS',
  FETCH_ALL_UNAPPROVED_FAILURE: 'FETCH_ALL_UNAPPROVED_QUOTES_FAILURE',
  LIKE: 'LIKE_QUOTE',
  LIKE_BEGIN: 'LIKE_QUOTE_BEGIN',
  LIKE_SUCCESS: 'LIKE_QUOTE_SUCCESS',
  LIKE_FAILURE: 'LIKE_QUOTE_FAILURE',
  UNLIKE: 'UNLIKE_QUOTE',
  UNLIKE_BEGIN: 'UNLIKE_QUOTE_BEGIN',
  UNLIKE_SUCCESS: 'UNLIKE_QUOTE_SUCCESS',
  UNLIKE_FAILURE: 'UNLIKE_QUOTE_FAILURE',
  APPROVE: 'APPROVE_QUOTE',
  APPROVE_BEGIN: 'APPROVE_QUOTE_BEGIN',
  APPROVE_SUCCESS: 'APPROVE_QUOTE_SUCCESS',
  APPROVE_FAILURE: 'APPROVE_QUOTE_FAILURE',
  UNAPPROVE: 'UNAPPROVE_QUOTE',
  UNAPPROVE_BEGIN: 'UNAPPROVE_QUOTE_BEGIN',
  UNAPPROVE_SUCCESS: 'UNAPPROVE_QUOTE_SUCCESS',
  UNAPPROVE_FAILURE: 'UNAPPROVE_QUOTE_FAILURE',
  DELETE: 'DELETE_QUOTE',
  DELETE_BEGIN: 'DELETE_QUOTE_BEGIN',
  DELETE_SUCCESS: 'DELETE_QUOTE_SUCCESS',
  DELETE_FAILURE: 'DELETE_QUOTE_FAILURE'
};

/**
 *
 */
export const Search = {
  SEARCH: 'Search.SEARCH',
  SEARCH_BEGIN: 'Search.SEARCH_BEGIN',
  SEARCH_FAILURE: 'Search.SEARCH_FAILURE',
  SEARCH_SUCCESS: 'Search.SEARCH_SUCCESS',
  RESULTS_RECEIVED: 'Search.RESULTS_RECEIVED'
};

/**
 *
 */
export const User = {
  FETCH: 'User.FETCH',
  FETCH_BEGIN: 'User.FETCH_BEGIN',
  FETCH_SUCCESS: 'User.FETCH_SUCCESS',
  FETCH_FAILURE: 'User.FETCH_FAILURE',
  UPDATE: 'User.UPDATE',
  UPDATE_BEGIN: 'User.UPDATE_BEGIN',
  UPDATE_SUCCESS: 'User.UPDATE_SUCCESS',
  UPDATE_FAILURE: 'User.UPDATE_FAILURE',
  LOGIN: 'User.LOGIN',
  LOGIN_BEGIN: 'User.LOGIN_BEGIN',
  LOGIN_SUCCESS: 'User.LOGIN_SUCCESS',
  LOGIN_FAILURE: 'User.LOGIN_FAILURE',
  LOGOUT: 'User.LOGOUT'
};
