// flow-typed signature: 152babc9769cef4b232ab238975889a3
// flow-typed version: <<STUB>>/animate.css_v^4.1.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'animate.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'animate.css' {
  declare module.exports: any;
}
