// flow-typed signature: 816eec7aaf96ae872806be6f60bef5fe
// flow-typed version: <<STUB>>/babel-plugin-transform-import-to-require_v^1.0.0/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-import-to-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-import-to-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'babel-plugin-transform-import-to-require/index' {
  declare module.exports: $Exports<'babel-plugin-transform-import-to-require'>;
}
declare module 'babel-plugin-transform-import-to-require/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-import-to-require'>;
}
