// flow-typed signature: 64527854b4110b24c3e352ce8a5694de
// flow-typed version: <<STUB>>/bunyan-pretty_v^0.0.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bunyan-pretty'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bunyan-pretty' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'bunyan-pretty/index' {
  declare module.exports: $Exports<'bunyan-pretty'>;
}
declare module 'bunyan-pretty/index.js' {
  declare module.exports: $Exports<'bunyan-pretty'>;
}
