// flow-typed signature: 6dea64dc62055c1a9b74710581bc8302
// flow-typed version: <<STUB>>/duplicate-package-checker-webpack-plugin_v^3.0.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'duplicate-package-checker-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'duplicate-package-checker-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'duplicate-package-checker-webpack-plugin/lib' {
  declare module.exports: any;
}

declare module 'duplicate-package-checker-webpack-plugin/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'duplicate-package-checker-webpack-plugin/lib/index' {
  declare module.exports: $Exports<'duplicate-package-checker-webpack-plugin/lib'>;
}
declare module 'duplicate-package-checker-webpack-plugin/lib/index.js' {
  declare module.exports: $Exports<'duplicate-package-checker-webpack-plugin/lib'>;
}
declare module 'duplicate-package-checker-webpack-plugin/src/index' {
  declare module.exports: $Exports<'duplicate-package-checker-webpack-plugin/src'>;
}
declare module 'duplicate-package-checker-webpack-plugin/src/index.js' {
  declare module.exports: $Exports<'duplicate-package-checker-webpack-plugin/src'>;
}
