// flow-typed signature: 7a35a78154fecc08bee20fb0a5593529
// flow-typed version: <<STUB>>/es6-promise-pool_v^2.5.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promise-pool'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promise-pool' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-promise-pool/es6-promise-pool' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-promise-pool/es6-promise-pool.js' {
  declare module.exports: $Exports<'es6-promise-pool/es6-promise-pool'>;
}
