// flow-typed signature: 130772f6c93a1ccfdda9e85656030ec3
// flow-typed version: <<STUB>>/fuzzy_v^0.1.3/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fuzzy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fuzzy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fuzzy/lib/fuzzy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fuzzy/lib/fuzzy.js' {
  declare module.exports: $Exports<'fuzzy/lib/fuzzy'>;
}
