// flow-typed signature: 77f3dbef2865eb518b16add3e6a13319
// flow-typed version: <<STUB>>/history_v^5.0.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'history'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'history' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'history/browser' {
  declare module.exports: any;
}

declare module 'history/hash' {
  declare module.exports: any;
}

declare module 'history/history.development' {
  declare module.exports: any;
}

declare module 'history/history.production.min' {
  declare module.exports: any;
}

declare module 'history/main' {
  declare module.exports: any;
}

declare module 'history/umd/history.development' {
  declare module.exports: any;
}

declare module 'history/umd/history.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'history/browser.js' {
  declare module.exports: $Exports<'history/browser'>;
}
declare module 'history/hash.js' {
  declare module.exports: $Exports<'history/hash'>;
}
declare module 'history/history.development.js' {
  declare module.exports: $Exports<'history/history.development'>;
}
declare module 'history/history.production.min.js' {
  declare module.exports: $Exports<'history/history.production.min'>;
}
declare module 'history/index' {
  declare module.exports: $Exports<'history'>;
}
declare module 'history/index.js' {
  declare module.exports: $Exports<'history'>;
}
declare module 'history/main.js' {
  declare module.exports: $Exports<'history/main'>;
}
declare module 'history/umd/history.development.js' {
  declare module.exports: $Exports<'history/umd/history.development'>;
}
declare module 'history/umd/history.production.min.js' {
  declare module.exports: $Exports<'history/umd/history.production.min'>;
}
