// flow-typed signature: a09be03f946f2554baf550673f53a9ad
// flow-typed version: <<STUB>>/is-hotkey_v^0.0.1/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-hotkey'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-hotkey' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'is-hotkey/lib/index' {
  declare module.exports: any;
}

declare module 'is-hotkey/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'is-hotkey/lib/index.js' {
  declare module.exports: $Exports<'is-hotkey/lib/index'>;
}
declare module 'is-hotkey/src/index.js' {
  declare module.exports: $Exports<'is-hotkey/src/index'>;
}
