// flow-typed signature: 79014d872afbdb59a0ded6716b083518
// flow-typed version: <<STUB>>/medium-draft_v^0.6.0-beta1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'medium-draft'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'medium-draft' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'medium-draft/dist/medium-draft-exporter' {
  declare module.exports: any;
}

declare module 'medium-draft/dist/medium-draft-importer' {
  declare module.exports: any;
}

declare module 'medium-draft/dist/medium-draft' {
  declare module.exports: any;
}

declare module 'medium-draft/example/index' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/addbutton' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocks/atomic' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocks/blockquotecaption' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocks/break' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocks/caption' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocks/image' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocks/text' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocks/todo' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/blocktoolbar' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/customrenderer' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/entities/link' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/inlinetoolbar' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/LinkEditComponent' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/sides/break' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/sides/image' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/stylebutton' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/components/toolbar' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/createEditor' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/editor' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/exporter' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/blockRendererFn' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/blockRenderMap' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/blockStyleFn' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/handleBeforeInput' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/handleKeyCommand' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/handlePastedText' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/handleReturn' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/index' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/keyBindingFn' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/onTab' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/handlers/onUpArrow' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/importer' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/index' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/model/content' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/model/index' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/util/beforeinput' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/util/blockStyleFn' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/util/constants' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/util/customstylemap' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/util/index' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/util/keybinding' {
  declare module.exports: any;
}

declare module 'medium-draft/lib/util/rendermap' {
  declare module.exports: any;
}

// Filename aliases
declare module 'medium-draft/dist/medium-draft-exporter.js' {
  declare module.exports: $Exports<'medium-draft/dist/medium-draft-exporter'>;
}
declare module 'medium-draft/dist/medium-draft-importer.js' {
  declare module.exports: $Exports<'medium-draft/dist/medium-draft-importer'>;
}
declare module 'medium-draft/dist/medium-draft.js' {
  declare module.exports: $Exports<'medium-draft/dist/medium-draft'>;
}
declare module 'medium-draft/example/index.js' {
  declare module.exports: $Exports<'medium-draft/example/index'>;
}
declare module 'medium-draft/lib/components/addbutton.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/addbutton'>;
}
declare module 'medium-draft/lib/components/blocks/atomic.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocks/atomic'>;
}
declare module 'medium-draft/lib/components/blocks/blockquotecaption.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocks/blockquotecaption'>;
}
declare module 'medium-draft/lib/components/blocks/break.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocks/break'>;
}
declare module 'medium-draft/lib/components/blocks/caption.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocks/caption'>;
}
declare module 'medium-draft/lib/components/blocks/image.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocks/image'>;
}
declare module 'medium-draft/lib/components/blocks/text.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocks/text'>;
}
declare module 'medium-draft/lib/components/blocks/todo.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocks/todo'>;
}
declare module 'medium-draft/lib/components/blocktoolbar.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/blocktoolbar'>;
}
declare module 'medium-draft/lib/components/customrenderer.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/customrenderer'>;
}
declare module 'medium-draft/lib/components/entities/link.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/entities/link'>;
}
declare module 'medium-draft/lib/components/inlinetoolbar.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/inlinetoolbar'>;
}
declare module 'medium-draft/lib/components/LinkEditComponent.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/LinkEditComponent'>;
}
declare module 'medium-draft/lib/components/sides/break.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/sides/break'>;
}
declare module 'medium-draft/lib/components/sides/image.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/sides/image'>;
}
declare module 'medium-draft/lib/components/stylebutton.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/stylebutton'>;
}
declare module 'medium-draft/lib/components/toolbar.js' {
  declare module.exports: $Exports<'medium-draft/lib/components/toolbar'>;
}
declare module 'medium-draft/lib/createEditor.js' {
  declare module.exports: $Exports<'medium-draft/lib/createEditor'>;
}
declare module 'medium-draft/lib/editor.js' {
  declare module.exports: $Exports<'medium-draft/lib/editor'>;
}
declare module 'medium-draft/lib/exporter.js' {
  declare module.exports: $Exports<'medium-draft/lib/exporter'>;
}
declare module 'medium-draft/lib/handlers/blockRendererFn.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/blockRendererFn'>;
}
declare module 'medium-draft/lib/handlers/blockRenderMap.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/blockRenderMap'>;
}
declare module 'medium-draft/lib/handlers/blockStyleFn.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/blockStyleFn'>;
}
declare module 'medium-draft/lib/handlers/handleBeforeInput.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/handleBeforeInput'>;
}
declare module 'medium-draft/lib/handlers/handleKeyCommand.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/handleKeyCommand'>;
}
declare module 'medium-draft/lib/handlers/handlePastedText.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/handlePastedText'>;
}
declare module 'medium-draft/lib/handlers/handleReturn.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/handleReturn'>;
}
declare module 'medium-draft/lib/handlers/index.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/index'>;
}
declare module 'medium-draft/lib/handlers/keyBindingFn.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/keyBindingFn'>;
}
declare module 'medium-draft/lib/handlers/onTab.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/onTab'>;
}
declare module 'medium-draft/lib/handlers/onUpArrow.js' {
  declare module.exports: $Exports<'medium-draft/lib/handlers/onUpArrow'>;
}
declare module 'medium-draft/lib/importer.js' {
  declare module.exports: $Exports<'medium-draft/lib/importer'>;
}
declare module 'medium-draft/lib/index.js' {
  declare module.exports: $Exports<'medium-draft/lib/index'>;
}
declare module 'medium-draft/lib/model/content.js' {
  declare module.exports: $Exports<'medium-draft/lib/model/content'>;
}
declare module 'medium-draft/lib/model/index.js' {
  declare module.exports: $Exports<'medium-draft/lib/model/index'>;
}
declare module 'medium-draft/lib/util/beforeinput.js' {
  declare module.exports: $Exports<'medium-draft/lib/util/beforeinput'>;
}
declare module 'medium-draft/lib/util/blockStyleFn.js' {
  declare module.exports: $Exports<'medium-draft/lib/util/blockStyleFn'>;
}
declare module 'medium-draft/lib/util/constants.js' {
  declare module.exports: $Exports<'medium-draft/lib/util/constants'>;
}
declare module 'medium-draft/lib/util/customstylemap.js' {
  declare module.exports: $Exports<'medium-draft/lib/util/customstylemap'>;
}
declare module 'medium-draft/lib/util/index.js' {
  declare module.exports: $Exports<'medium-draft/lib/util/index'>;
}
declare module 'medium-draft/lib/util/keybinding.js' {
  declare module.exports: $Exports<'medium-draft/lib/util/keybinding'>;
}
declare module 'medium-draft/lib/util/rendermap.js' {
  declare module.exports: $Exports<'medium-draft/lib/util/rendermap'>;
}
