// flow-typed signature: e1ffbb1b76b73695fa2de6576635cad4
// flow-typed version: <<STUB>>/minireset.css_v^0.0.3/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minireset.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minireset.css' {
  declare module.exports: any;
}
