// flow-typed signature: ab11f096eed89ec66efdff54a1fcba4f
// flow-typed version: <<STUB>>/minireset.css_v0.0.2/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minireset.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'minireset.css' {
  declare module.exports: any;
}
