// flow-typed signature: 13a05f71c49a63f73f27a07dc60aea2d
// flow-typed version: <<STUB>>/minireset.css_v^0.0.3/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'minireset.css'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'minireset.css' {
  declare module.exports: any;
}
