// flow-typed signature: d3111469b2955331e427e18402062e23
// flow-typed version: <<STUB>>/rc-select_v^6.7.3/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rc-select'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rc-select' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rc-select/lib/DropdownMenu' {
  declare module.exports: any;
}

declare module 'rc-select/lib/FilterMixin' {
  declare module.exports: any;
}

declare module 'rc-select/lib/index' {
  declare module.exports: any;
}

declare module 'rc-select/lib/OptGroup' {
  declare module.exports: any;
}

declare module 'rc-select/lib/Option' {
  declare module.exports: any;
}

declare module 'rc-select/lib/PropTypes' {
  declare module.exports: any;
}

declare module 'rc-select/lib/Select' {
  declare module.exports: any;
}

declare module 'rc-select/lib/SelectTrigger' {
  declare module.exports: any;
}

declare module 'rc-select/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rc-select/lib/DropdownMenu.js' {
  declare module.exports: $Exports<'rc-select/lib/DropdownMenu'>;
}
declare module 'rc-select/lib/FilterMixin.js' {
  declare module.exports: $Exports<'rc-select/lib/FilterMixin'>;
}
declare module 'rc-select/lib/index.js' {
  declare module.exports: $Exports<'rc-select/lib/index'>;
}
declare module 'rc-select/lib/OptGroup.js' {
  declare module.exports: $Exports<'rc-select/lib/OptGroup'>;
}
declare module 'rc-select/lib/Option.js' {
  declare module.exports: $Exports<'rc-select/lib/Option'>;
}
declare module 'rc-select/lib/PropTypes.js' {
  declare module.exports: $Exports<'rc-select/lib/PropTypes'>;
}
declare module 'rc-select/lib/Select.js' {
  declare module.exports: $Exports<'rc-select/lib/Select'>;
}
declare module 'rc-select/lib/SelectTrigger.js' {
  declare module.exports: $Exports<'rc-select/lib/SelectTrigger'>;
}
declare module 'rc-select/lib/util.js' {
  declare module.exports: $Exports<'rc-select/lib/util'>;
}
