// flow-typed signature: b5b325ad0c260ad4a2670eeb87716dd5
// flow-typed version: <<STUB>>/react-textarea-autosize_v^8.3.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-textarea-autosize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-textarea-autosize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-textarea-autosize/dist/react-textarea-autosize.browser.cjs' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.browser.esm' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.dev' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.prod' {
  declare module.exports: any;
}

declare module 'react-textarea-autosize/dist/react-textarea-autosize.esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-textarea-autosize/dist/react-textarea-autosize.browser.cjs.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.browser.cjs'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.browser.esm.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.browser.esm'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.dev.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.cjs.dev'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.cjs'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.cjs.prod.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.cjs.prod'>;
}
declare module 'react-textarea-autosize/dist/react-textarea-autosize.esm.js' {
  declare module.exports: $Exports<'react-textarea-autosize/dist/react-textarea-autosize.esm'>;
}
