// flow-typed signature: 45f9c6eda51db40fcde1ca8bc0eef4e6
// flow-typed version: <<STUB>>/react-phone-number-input_v^3.1.4/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-phone-number-input'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-phone-number-input' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-phone-number-input/bundle/react-phone-number-input-input-max' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-input-mobile' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-input' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-max' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input-mobile' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/bundle/react-phone-number-input' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/CountryIcon' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/CountrySelect' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/Flag' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/countries' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/countries.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/getInternationalPhoneNumberPrefix' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/getInternationalPhoneNumberPrefix.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/getPhoneInputWithCountryStateUpdateFromNewProps' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/inputValuePrefix' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/inputValuePrefix.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/phoneInputHelpers' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/helpers/phoneInputHelpers.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InputBasic' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InputSmart' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/InternationalIcon' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumber.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumberDefaultMetadata.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumberDefaultMetadata.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumber.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumberDefaultMetadata.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputWithCountry' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PhoneInputWithCountryDefault' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/PropTypes' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/react-native/PhoneInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/react-native/PhoneTextInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/commonjs/usePhoneDigits' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/core/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/core' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/flags/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/flags' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input-core/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input-core' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input-max/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input-max' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input-mobile/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input-mobile' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/input' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/max/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/max' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/min/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/min' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/mobile/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/mobile' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/CountryIcon' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/CountrySelect' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/Flag' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/countries' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/countries.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/getInternationalPhoneNumberPrefix' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/getInternationalPhoneNumberPrefix.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/getPhoneInputWithCountryStateUpdateFromNewProps' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/inputValuePrefix' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/inputValuePrefix.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/phoneInputHelpers' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/helpers/phoneInputHelpers.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InputBasic' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InputSmart' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/InternationalIcon' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumber.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumberDefaultMetadata.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumber.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumberDefaultMetadata.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumber' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumber.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumberDefaultMetadata' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumberDefaultMetadata.test' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputWithCountry' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PhoneInputWithCountryDefault' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/PropTypes' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/react-native/PhoneInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/react-native/PhoneTextInput' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/modules/usePhoneDigits' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-native-input/index.commonjs' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-native-input' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/react-styleguidist' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/rollup.config' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/runnable/build-bundle-styles' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/runnable/fix-locales' {
  declare module.exports: any;
}

declare module 'react-phone-number-input/runnable/verify-flag-existence' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-phone-number-input/bundle/react-phone-number-input-input-max.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-input-max'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-input-mobile.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-input-mobile'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-input.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-input'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-max.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-max'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input-mobile.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input-mobile'>;
}
declare module 'react-phone-number-input/bundle/react-phone-number-input.js' {
  declare module.exports: $Exports<'react-phone-number-input/bundle/react-phone-number-input'>;
}
declare module 'react-phone-number-input/commonjs/CountryIcon.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/CountryIcon'>;
}
declare module 'react-phone-number-input/commonjs/CountrySelect.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/CountrySelect'>;
}
declare module 'react-phone-number-input/commonjs/Flag.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/Flag'>;
}
declare module 'react-phone-number-input/commonjs/helpers/countries.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/countries'>;
}
declare module 'react-phone-number-input/commonjs/helpers/countries.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/countries.test'>;
}
declare module 'react-phone-number-input/commonjs/helpers/getInternationalPhoneNumberPrefix.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/getInternationalPhoneNumberPrefix'>;
}
declare module 'react-phone-number-input/commonjs/helpers/getInternationalPhoneNumberPrefix.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/getInternationalPhoneNumberPrefix.test'>;
}
declare module 'react-phone-number-input/commonjs/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/getPhoneInputWithCountryStateUpdateFromNewProps'>;
}
declare module 'react-phone-number-input/commonjs/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.test'>;
}
declare module 'react-phone-number-input/commonjs/helpers/inputValuePrefix.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/inputValuePrefix'>;
}
declare module 'react-phone-number-input/commonjs/helpers/inputValuePrefix.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/inputValuePrefix.test'>;
}
declare module 'react-phone-number-input/commonjs/helpers/phoneInputHelpers.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/phoneInputHelpers'>;
}
declare module 'react-phone-number-input/commonjs/helpers/phoneInputHelpers.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/helpers/phoneInputHelpers.test'>;
}
declare module 'react-phone-number-input/commonjs/InputBasic.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InputBasic'>;
}
declare module 'react-phone-number-input/commonjs/InputSmart.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InputSmart'>;
}
declare module 'react-phone-number-input/commonjs/InternationalIcon.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/InternationalIcon'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumber'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumber.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumber.test'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumberDefaultMetadata.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/formatPhoneNumberDefaultMetadata.test'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumber'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumber.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumber.test'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumberDefaultMetadata.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isPossiblePhoneNumberDefaultMetadata.test'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumber'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumber.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumber.test'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumberDefaultMetadata.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/libphonenumber/isValidPhoneNumberDefaultMetadata.test'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInput'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputWithCountry.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputWithCountry'>;
}
declare module 'react-phone-number-input/commonjs/PhoneInputWithCountryDefault.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PhoneInputWithCountryDefault'>;
}
declare module 'react-phone-number-input/commonjs/PropTypes.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/PropTypes'>;
}
declare module 'react-phone-number-input/commonjs/react-native/PhoneInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/react-native/PhoneInput'>;
}
declare module 'react-phone-number-input/commonjs/react-native/PhoneTextInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/react-native/PhoneTextInput'>;
}
declare module 'react-phone-number-input/commonjs/usePhoneDigits.js' {
  declare module.exports: $Exports<'react-phone-number-input/commonjs/usePhoneDigits'>;
}
declare module 'react-phone-number-input/core/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/core/index.commonjs'>;
}
declare module 'react-phone-number-input/core/index' {
  declare module.exports: $Exports<'react-phone-number-input/core'>;
}
declare module 'react-phone-number-input/core/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/core'>;
}
declare module 'react-phone-number-input/flags/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/flags/index.commonjs'>;
}
declare module 'react-phone-number-input/flags/index' {
  declare module.exports: $Exports<'react-phone-number-input/flags'>;
}
declare module 'react-phone-number-input/flags/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/flags'>;
}
declare module 'react-phone-number-input/input-core/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/input-core/index.commonjs'>;
}
declare module 'react-phone-number-input/input-core/index' {
  declare module.exports: $Exports<'react-phone-number-input/input-core'>;
}
declare module 'react-phone-number-input/input-core/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/input-core'>;
}
declare module 'react-phone-number-input/input-max/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/input-max/index.commonjs'>;
}
declare module 'react-phone-number-input/input-max/index' {
  declare module.exports: $Exports<'react-phone-number-input/input-max'>;
}
declare module 'react-phone-number-input/input-max/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/input-max'>;
}
declare module 'react-phone-number-input/input-mobile/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/input-mobile/index.commonjs'>;
}
declare module 'react-phone-number-input/input-mobile/index' {
  declare module.exports: $Exports<'react-phone-number-input/input-mobile'>;
}
declare module 'react-phone-number-input/input-mobile/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/input-mobile'>;
}
declare module 'react-phone-number-input/input/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/input/index.commonjs'>;
}
declare module 'react-phone-number-input/input/index' {
  declare module.exports: $Exports<'react-phone-number-input/input'>;
}
declare module 'react-phone-number-input/input/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/input'>;
}
declare module 'react-phone-number-input/max/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/max/index.commonjs'>;
}
declare module 'react-phone-number-input/max/index' {
  declare module.exports: $Exports<'react-phone-number-input/max'>;
}
declare module 'react-phone-number-input/max/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/max'>;
}
declare module 'react-phone-number-input/min/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/min/index.commonjs'>;
}
declare module 'react-phone-number-input/min/index' {
  declare module.exports: $Exports<'react-phone-number-input/min'>;
}
declare module 'react-phone-number-input/min/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/min'>;
}
declare module 'react-phone-number-input/mobile/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/mobile/index.commonjs'>;
}
declare module 'react-phone-number-input/mobile/index' {
  declare module.exports: $Exports<'react-phone-number-input/mobile'>;
}
declare module 'react-phone-number-input/mobile/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/mobile'>;
}
declare module 'react-phone-number-input/modules/CountryIcon.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/CountryIcon'>;
}
declare module 'react-phone-number-input/modules/CountrySelect.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/CountrySelect'>;
}
declare module 'react-phone-number-input/modules/Flag.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/Flag'>;
}
declare module 'react-phone-number-input/modules/helpers/countries.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/countries'>;
}
declare module 'react-phone-number-input/modules/helpers/countries.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/countries.test'>;
}
declare module 'react-phone-number-input/modules/helpers/getInternationalPhoneNumberPrefix.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/getInternationalPhoneNumberPrefix'>;
}
declare module 'react-phone-number-input/modules/helpers/getInternationalPhoneNumberPrefix.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/getInternationalPhoneNumberPrefix.test'>;
}
declare module 'react-phone-number-input/modules/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/getPhoneInputWithCountryStateUpdateFromNewProps'>;
}
declare module 'react-phone-number-input/modules/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/getPhoneInputWithCountryStateUpdateFromNewProps.test'>;
}
declare module 'react-phone-number-input/modules/helpers/inputValuePrefix.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/inputValuePrefix'>;
}
declare module 'react-phone-number-input/modules/helpers/inputValuePrefix.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/inputValuePrefix.test'>;
}
declare module 'react-phone-number-input/modules/helpers/phoneInputHelpers.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/phoneInputHelpers'>;
}
declare module 'react-phone-number-input/modules/helpers/phoneInputHelpers.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/helpers/phoneInputHelpers.test'>;
}
declare module 'react-phone-number-input/modules/InputBasic.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InputBasic'>;
}
declare module 'react-phone-number-input/modules/InputSmart.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InputSmart'>;
}
declare module 'react-phone-number-input/modules/InternationalIcon.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/InternationalIcon'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/formatPhoneNumber'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumber.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/formatPhoneNumber.test'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/formatPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/formatPhoneNumberDefaultMetadata.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/formatPhoneNumberDefaultMetadata.test'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumber'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumber.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumber.test'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumberDefaultMetadata.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isPossiblePhoneNumberDefaultMetadata.test'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumber.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isValidPhoneNumber'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumber.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isValidPhoneNumber.test'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumberDefaultMetadata.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isValidPhoneNumberDefaultMetadata'>;
}
declare module 'react-phone-number-input/modules/libphonenumber/isValidPhoneNumberDefaultMetadata.test.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/libphonenumber/isValidPhoneNumberDefaultMetadata.test'>;
}
declare module 'react-phone-number-input/modules/PhoneInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInput'>;
}
declare module 'react-phone-number-input/modules/PhoneInputWithCountry.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputWithCountry'>;
}
declare module 'react-phone-number-input/modules/PhoneInputWithCountryDefault.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PhoneInputWithCountryDefault'>;
}
declare module 'react-phone-number-input/modules/PropTypes.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/PropTypes'>;
}
declare module 'react-phone-number-input/modules/react-native/PhoneInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/react-native/PhoneInput'>;
}
declare module 'react-phone-number-input/modules/react-native/PhoneTextInput.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/react-native/PhoneTextInput'>;
}
declare module 'react-phone-number-input/modules/usePhoneDigits.js' {
  declare module.exports: $Exports<'react-phone-number-input/modules/usePhoneDigits'>;
}
declare module 'react-phone-number-input/react-native-input/index.commonjs.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-native-input/index.commonjs'>;
}
declare module 'react-phone-number-input/react-native-input/index' {
  declare module.exports: $Exports<'react-phone-number-input/react-native-input'>;
}
declare module 'react-phone-number-input/react-native-input/index.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-native-input'>;
}
declare module 'react-phone-number-input/react-styleguidist.js' {
  declare module.exports: $Exports<'react-phone-number-input/react-styleguidist'>;
}
declare module 'react-phone-number-input/rollup.config.js' {
  declare module.exports: $Exports<'react-phone-number-input/rollup.config'>;
}
declare module 'react-phone-number-input/runnable/build-bundle-styles.js' {
  declare module.exports: $Exports<'react-phone-number-input/runnable/build-bundle-styles'>;
}
declare module 'react-phone-number-input/runnable/fix-locales.js' {
  declare module.exports: $Exports<'react-phone-number-input/runnable/fix-locales'>;
}
declare module 'react-phone-number-input/runnable/verify-flag-existence.js' {
  declare module.exports: $Exports<'react-phone-number-input/runnable/verify-flag-existence'>;
}
