// flow-typed signature: de8aa0d9a6778d2f446c2d842712d241
// flow-typed version: <<STUB>>/react-portal_v^3.1.0/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-portal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-portal' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-portal/build/examples_bundle' {
  declare module.exports: any;
}

declare module 'react-portal/build/portal' {
  declare module.exports: any;
}

declare module 'react-portal/lib/portal' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-portal/build/examples_bundle.js' {
  declare module.exports: $Exports<'react-portal/build/examples_bundle'>;
}
declare module 'react-portal/build/portal.js' {
  declare module.exports: $Exports<'react-portal/build/portal'>;
}
declare module 'react-portal/lib/portal.js' {
  declare module.exports: $Exports<'react-portal/lib/portal'>;
}
