// flow-typed signature: 6f4aeb9e94c6c1872bb0cfa75d3d7181
// flow-typed version: <<STUB>>/react-tagcloud_v^2.0.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tagcloud'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tagcloud' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tagcloud/__tests__/defaultRenderer-test' {
  declare module.exports: any;
}

declare module 'react-tagcloud/__tests__/helpers-test' {
  declare module.exports: any;
}

declare module 'react-tagcloud/__tests__/setupTests' {
  declare module.exports: any;
}

declare module 'react-tagcloud/__tests__/TagCloud-test' {
  declare module.exports: any;
}

declare module 'react-tagcloud/__tests__/utils' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/analytics' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/App' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/custom-color-options' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/custom-renderer' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/custom-styles' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/interactive-cloud' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/shuffle-with-seed' {
  declare module.exports: any;
}

declare module 'react-tagcloud/examples/src/simple-cloud' {
  declare module.exports: any;
}

declare module 'react-tagcloud/lib/default-renderer' {
  declare module.exports: any;
}

declare module 'react-tagcloud/lib/defaultRenderer' {
  declare module.exports: any;
}

declare module 'react-tagcloud/lib/helpers' {
  declare module.exports: any;
}

declare module 'react-tagcloud/lib' {
  declare module.exports: any;
}

declare module 'react-tagcloud/lib/tag-cloud' {
  declare module.exports: any;
}

declare module 'react-tagcloud/lib/TagCloud' {
  declare module.exports: any;
}

declare module 'react-tagcloud/lib/TagCloudOld' {
  declare module.exports: any;
}

declare module 'react-tagcloud/src/defaultRenderer' {
  declare module.exports: any;
}

declare module 'react-tagcloud/src/helpers' {
  declare module.exports: any;
}

declare module 'react-tagcloud/src' {
  declare module.exports: any;
}

declare module 'react-tagcloud/src/TagCloud' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tagcloud/__tests__/defaultRenderer-test.js' {
  declare module.exports: $Exports<'react-tagcloud/__tests__/defaultRenderer-test'>;
}
declare module 'react-tagcloud/__tests__/helpers-test.js' {
  declare module.exports: $Exports<'react-tagcloud/__tests__/helpers-test'>;
}
declare module 'react-tagcloud/__tests__/setupTests.js' {
  declare module.exports: $Exports<'react-tagcloud/__tests__/setupTests'>;
}
declare module 'react-tagcloud/__tests__/TagCloud-test.js' {
  declare module.exports: $Exports<'react-tagcloud/__tests__/TagCloud-test'>;
}
declare module 'react-tagcloud/__tests__/utils.js' {
  declare module.exports: $Exports<'react-tagcloud/__tests__/utils'>;
}
declare module 'react-tagcloud/examples/src/analytics.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/analytics'>;
}
declare module 'react-tagcloud/examples/src/App.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/App'>;
}
declare module 'react-tagcloud/examples/src/custom-color-options.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/custom-color-options'>;
}
declare module 'react-tagcloud/examples/src/custom-renderer.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/custom-renderer'>;
}
declare module 'react-tagcloud/examples/src/custom-styles.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/custom-styles'>;
}
declare module 'react-tagcloud/examples/src/index' {
  declare module.exports: $Exports<'react-tagcloud/examples/src'>;
}
declare module 'react-tagcloud/examples/src/index.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src'>;
}
declare module 'react-tagcloud/examples/src/interactive-cloud.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/interactive-cloud'>;
}
declare module 'react-tagcloud/examples/src/shuffle-with-seed.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/shuffle-with-seed'>;
}
declare module 'react-tagcloud/examples/src/simple-cloud.js' {
  declare module.exports: $Exports<'react-tagcloud/examples/src/simple-cloud'>;
}
declare module 'react-tagcloud/lib/default-renderer.js' {
  declare module.exports: $Exports<'react-tagcloud/lib/default-renderer'>;
}
declare module 'react-tagcloud/lib/defaultRenderer.js' {
  declare module.exports: $Exports<'react-tagcloud/lib/defaultRenderer'>;
}
declare module 'react-tagcloud/lib/helpers.js' {
  declare module.exports: $Exports<'react-tagcloud/lib/helpers'>;
}
declare module 'react-tagcloud/lib/index' {
  declare module.exports: $Exports<'react-tagcloud/lib'>;
}
declare module 'react-tagcloud/lib/index.js' {
  declare module.exports: $Exports<'react-tagcloud/lib'>;
}
declare module 'react-tagcloud/lib/tag-cloud.js' {
  declare module.exports: $Exports<'react-tagcloud/lib/tag-cloud'>;
}
declare module 'react-tagcloud/lib/TagCloud.js' {
  declare module.exports: $Exports<'react-tagcloud/lib/TagCloud'>;
}
declare module 'react-tagcloud/lib/TagCloudOld.js' {
  declare module.exports: $Exports<'react-tagcloud/lib/TagCloudOld'>;
}
declare module 'react-tagcloud/src/defaultRenderer.js' {
  declare module.exports: $Exports<'react-tagcloud/src/defaultRenderer'>;
}
declare module 'react-tagcloud/src/helpers.js' {
  declare module.exports: $Exports<'react-tagcloud/src/helpers'>;
}
declare module 'react-tagcloud/src/index' {
  declare module.exports: $Exports<'react-tagcloud/src'>;
}
declare module 'react-tagcloud/src/index.js' {
  declare module.exports: $Exports<'react-tagcloud/src'>;
}
declare module 'react-tagcloud/src/TagCloud.js' {
  declare module.exports: $Exports<'react-tagcloud/src/TagCloud'>;
}
