// flow-typed signature: 25b20e8dba283557eba4ef4fd260a83f
// flow-typed version: <<STUB>>/react-collapse_v^5.0.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-collapse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-collapse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-collapse/build/react-collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/build/react-collapse.min' {
  declare module.exports: any;
}

declare module 'react-collapse/lib/Collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/lib' {
  declare module.exports: any;
}

declare module 'react-collapse/lib/UnmountClosed' {
  declare module.exports: any;
}

declare module 'react-collapse/src/Collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/src' {
  declare module.exports: any;
}

declare module 'react-collapse/src/UnmountClosed' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-collapse/build/react-collapse.js' {
  declare module.exports: $Exports<'react-collapse/build/react-collapse'>;
}
declare module 'react-collapse/build/react-collapse.min.js' {
  declare module.exports: $Exports<'react-collapse/build/react-collapse.min'>;
}
declare module 'react-collapse/lib/Collapse.js' {
  declare module.exports: $Exports<'react-collapse/lib/Collapse'>;
}
declare module 'react-collapse/lib/index' {
  declare module.exports: $Exports<'react-collapse/lib'>;
}
declare module 'react-collapse/lib/index.js' {
  declare module.exports: $Exports<'react-collapse/lib'>;
}
declare module 'react-collapse/lib/UnmountClosed.js' {
  declare module.exports: $Exports<'react-collapse/lib/UnmountClosed'>;
}
declare module 'react-collapse/src/Collapse.js' {
  declare module.exports: $Exports<'react-collapse/src/Collapse'>;
}
declare module 'react-collapse/src/index' {
  declare module.exports: $Exports<'react-collapse/src'>;
}
declare module 'react-collapse/src/index.js' {
  declare module.exports: $Exports<'react-collapse/src'>;
}
declare module 'react-collapse/src/UnmountClosed.js' {
  declare module.exports: $Exports<'react-collapse/src/UnmountClosed'>;
}
