// flow-typed signature: 2a2ebc3fa5ed13781b5e2fcb4058613d
// flow-typed version: <<STUB>>/react-styleguidist_v^9.0.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-styleguidist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-styleguidist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-styleguidist/lib/bin/styleguidist' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/consts' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/polyfills' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Argument/ArgumentRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Argument/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Arguments/ArgumentsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Arguments/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Code/CodeRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Code/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Components/Components' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Components/ComponentsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Components/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsList' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsListRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ComponentsList/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Editor/Editor' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Editor/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Error/ErrorRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Error/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ExamplePlaceholder/ExamplePlaceholderRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ExamplePlaceholder/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Examples/Examples' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Examples/ExamplesRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Examples/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Heading/HeadingRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Heading/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/JsDoc/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/JsDoc/JsDoc' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Link/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Link/LinkRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Logo/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Logo/LogoRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Blockquote/BlockquoteRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Blockquote/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Checkbox/CheckboxRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Checkbox/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsSummaryRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Details/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Hr/HrRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Hr/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/List/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/List/ListRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Markdown' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading/MarkdownHeadingRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Pre/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Pre/PreRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableBodyRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableCellRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableHeadRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRowRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Message/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Message/MessageRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Methods/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Methods/MethodsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Name/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Name/NameRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/NotFound/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/NotFound/NotFoundRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Para/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Para/ParaRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Pathline/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Pathline/PathlineRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Playground/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Playground/Playground' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Playground/PlaygroundRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/PlaygroundError/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/PlaygroundError/PlaygroundErrorRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Preview/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Preview/Preview' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Props/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Props/PropsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Props/util' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ReactComponent/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponent' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponentRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ReactExample/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ReactExample/ReactExample' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Ribbon/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Ribbon/Ribbon' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Ribbon/RibbonRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Section/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Section/Section' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Section/SectionRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/SectionHeading/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/SectionHeading/SectionHeading' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/SectionHeading/SectionHeadingRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Sections/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Sections/Sections' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Sections/SectionsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Slot/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Slot/Slot' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/slots/CodeTabButton' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/slots/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/slots/IsolateButton' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/slots/UsageTabButton' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Styled/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Styled/Styled' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/StyleGuide/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuide' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuideRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/TabButton/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/TabButton/TabButtonRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Table/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Table/TableRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/TableOfContents/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContents' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContentsRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Text/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Text/TextRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ToolbarButton/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/ToolbarButton/ToolbarButtonRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Type/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Type/TypeRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Usage/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Usage/Usage' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Version/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Version/VersionRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Welcome/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Welcome/WelcomeRenderer' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Wrapper/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/rsg-components/Wrapper/Wrapper' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/styles/createStyleSheet' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/styles/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/styles/nonInheritedProps' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/styles/prismTheme' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/styles/setupjss' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/styles/styles' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/styles/theme' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/compileCode' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/filterComponentExamples' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/filterComponentsByExactName' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/filterComponentsByName' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/filterComponentsInSectionsByExactName' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/filterSectionExamples' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/filterSectionsByName' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/findSection' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/getAst' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/getComponent' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/getFilterRegExp' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/getInfoFromHash' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/getPageTitle' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/getRouteData' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/getUrl' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/handleHash' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/processComponents' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/processSections' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/renderStyleguide' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/rewriteImports' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/splitExampleCode' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/client/utils/transpileImports' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/examples-loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/props-loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/styleguide-loader' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/chunkify' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/client/evalInContext' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/client/requireInRuntime' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/expandDefaultComponent' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/filterComponentsWithExample' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getAllContentPages' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getAst' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getComponentFiles' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getComponentFilesFromSections' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getComponentPatternsFromSections' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getComponents' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getExamples' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getImports' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getNameFromFilePath' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getProps' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/getSections' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/highlightCode' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/highlightCodeInMarkdown' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/noAutoLinkRemarkPlugin' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/parseExample' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/processComponent' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/removeDoclets' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/requireIt' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/slugger' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/loaders/utils/sortProps' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/__mocks__/build' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/__mocks__/server' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/build' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/config' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/consts' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/create-server' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/index' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/logger' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/make-webpack-config' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/schemas/config' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/server' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/ensureWebpack' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/error' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/findFileCaseInsensitive' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/findUserWebpackConfig' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/getUserPackageJson' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/getWebpackVersion' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/mergeWebpackConfig' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/sanitizeConfig' {
  declare module.exports: any;
}

declare module 'react-styleguidist/lib/scripts/utils/StyleguidistOptionsPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-styleguidist/lib/bin/styleguidist.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/bin/styleguidist'>;
}
declare module 'react-styleguidist/lib/client/consts.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/consts'>;
}
declare module 'react-styleguidist/lib/client/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/index'>;
}
declare module 'react-styleguidist/lib/client/polyfills.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/polyfills'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Argument/ArgumentRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Argument/ArgumentRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Argument/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Argument/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Arguments/ArgumentsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Arguments/ArgumentsRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Arguments/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Arguments/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Code/CodeRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Code/CodeRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Code/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Code/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Components/Components.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Components/Components'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Components/ComponentsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Components/ComponentsRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Components/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Components/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsList.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsList'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsListRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ComponentsList/ComponentsListRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ComponentsList/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ComponentsList/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Editor/Editor.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Editor/Editor'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Editor/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Editor/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Error/ErrorRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Error/ErrorRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Error/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Error/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ExamplePlaceholder/ExamplePlaceholderRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ExamplePlaceholder/ExamplePlaceholderRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ExamplePlaceholder/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ExamplePlaceholder/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Examples/Examples.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Examples/Examples'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Examples/ExamplesRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Examples/ExamplesRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Examples/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Examples/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Heading/HeadingRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Heading/HeadingRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Heading/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Heading/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/JsDoc/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/JsDoc/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/JsDoc/JsDoc.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/JsDoc/JsDoc'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Link/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Link/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Link/LinkRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Link/LinkRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Logo/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Logo/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Logo/LogoRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Logo/LogoRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Blockquote/BlockquoteRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Blockquote/BlockquoteRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Blockquote/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Blockquote/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Checkbox/CheckboxRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Checkbox/CheckboxRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Checkbox/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Checkbox/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsSummaryRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Details/DetailsSummaryRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Details/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Details/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Hr/HrRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Hr/HrRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Hr/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Hr/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/List/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/List/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/List/ListRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/List/ListRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Markdown.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Markdown'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading/MarkdownHeadingRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/MarkdownHeading/MarkdownHeadingRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Pre/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Pre/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Pre/PreRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Pre/PreRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Table/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableBodyRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableBodyRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableCellRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableCellRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableHeadRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableHeadRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRowRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Markdown/Table/TableRowRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Message/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Message/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Message/MessageRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Message/MessageRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Methods/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Methods/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Methods/MethodsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Methods/MethodsRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Name/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Name/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Name/NameRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Name/NameRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/NotFound/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/NotFound/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/NotFound/NotFoundRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/NotFound/NotFoundRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Para/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Para/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Para/ParaRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Para/ParaRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Pathline/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Pathline/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Pathline/PathlineRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Pathline/PathlineRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Playground/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Playground/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Playground/Playground.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Playground/Playground'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Playground/PlaygroundRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Playground/PlaygroundRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/PlaygroundError/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/PlaygroundError/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/PlaygroundError/PlaygroundErrorRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/PlaygroundError/PlaygroundErrorRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Preview/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Preview/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Preview/Preview.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Preview/Preview'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Props/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Props/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Props/PropsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Props/PropsRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Props/util.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Props/util'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ReactComponent/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ReactComponent/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponent.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponent'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponentRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ReactComponent/ReactComponentRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ReactExample/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ReactExample/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ReactExample/ReactExample.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ReactExample/ReactExample'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Ribbon/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Ribbon/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Ribbon/Ribbon.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Ribbon/Ribbon'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Ribbon/RibbonRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Ribbon/RibbonRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Section/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Section/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Section/Section.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Section/Section'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Section/SectionRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Section/SectionRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/SectionHeading/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/SectionHeading/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/SectionHeading/SectionHeading.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/SectionHeading/SectionHeading'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/SectionHeading/SectionHeadingRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/SectionHeading/SectionHeadingRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Sections/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Sections/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Sections/Sections.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Sections/Sections'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Sections/SectionsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Sections/SectionsRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Slot/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Slot/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Slot/Slot.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Slot/Slot'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/slots/CodeTabButton.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/slots/CodeTabButton'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/slots/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/slots/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/slots/IsolateButton.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/slots/IsolateButton'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/slots/UsageTabButton.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/slots/UsageTabButton'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Styled/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Styled/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Styled/Styled.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Styled/Styled'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/StyleGuide/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/StyleGuide/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuide.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuide'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuideRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/StyleGuide/StyleGuideRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/TabButton/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/TabButton/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/TabButton/TabButtonRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/TabButton/TabButtonRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Table/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Table/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Table/TableRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Table/TableRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/TableOfContents/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/TableOfContents/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContents.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContents'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContentsRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/TableOfContents/TableOfContentsRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Text/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Text/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Text/TextRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Text/TextRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ToolbarButton/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ToolbarButton/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/ToolbarButton/ToolbarButtonRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/ToolbarButton/ToolbarButtonRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Type/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Type/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Type/TypeRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Type/TypeRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Usage/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Usage/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Usage/Usage.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Usage/Usage'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Version/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Version/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Version/VersionRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Version/VersionRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Welcome/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Welcome/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Welcome/WelcomeRenderer.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Welcome/WelcomeRenderer'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Wrapper/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Wrapper/index'>;
}
declare module 'react-styleguidist/lib/client/rsg-components/Wrapper/Wrapper.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/rsg-components/Wrapper/Wrapper'>;
}
declare module 'react-styleguidist/lib/client/styles/createStyleSheet.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/styles/createStyleSheet'>;
}
declare module 'react-styleguidist/lib/client/styles/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/styles/index'>;
}
declare module 'react-styleguidist/lib/client/styles/nonInheritedProps.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/styles/nonInheritedProps'>;
}
declare module 'react-styleguidist/lib/client/styles/prismTheme.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/styles/prismTheme'>;
}
declare module 'react-styleguidist/lib/client/styles/setupjss.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/styles/setupjss'>;
}
declare module 'react-styleguidist/lib/client/styles/styles.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/styles/styles'>;
}
declare module 'react-styleguidist/lib/client/styles/theme.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/styles/theme'>;
}
declare module 'react-styleguidist/lib/client/utils/compileCode.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/compileCode'>;
}
declare module 'react-styleguidist/lib/client/utils/filterComponentExamples.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/filterComponentExamples'>;
}
declare module 'react-styleguidist/lib/client/utils/filterComponentsByExactName.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/filterComponentsByExactName'>;
}
declare module 'react-styleguidist/lib/client/utils/filterComponentsByName.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/filterComponentsByName'>;
}
declare module 'react-styleguidist/lib/client/utils/filterComponentsInSectionsByExactName.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/filterComponentsInSectionsByExactName'>;
}
declare module 'react-styleguidist/lib/client/utils/filterSectionExamples.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/filterSectionExamples'>;
}
declare module 'react-styleguidist/lib/client/utils/filterSectionsByName.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/filterSectionsByName'>;
}
declare module 'react-styleguidist/lib/client/utils/findSection.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/findSection'>;
}
declare module 'react-styleguidist/lib/client/utils/getAst.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/getAst'>;
}
declare module 'react-styleguidist/lib/client/utils/getComponent.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/getComponent'>;
}
declare module 'react-styleguidist/lib/client/utils/getFilterRegExp.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/getFilterRegExp'>;
}
declare module 'react-styleguidist/lib/client/utils/getInfoFromHash.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/getInfoFromHash'>;
}
declare module 'react-styleguidist/lib/client/utils/getPageTitle.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/getPageTitle'>;
}
declare module 'react-styleguidist/lib/client/utils/getRouteData.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/getRouteData'>;
}
declare module 'react-styleguidist/lib/client/utils/getUrl.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/getUrl'>;
}
declare module 'react-styleguidist/lib/client/utils/handleHash.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/handleHash'>;
}
declare module 'react-styleguidist/lib/client/utils/processComponents.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/processComponents'>;
}
declare module 'react-styleguidist/lib/client/utils/processSections.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/processSections'>;
}
declare module 'react-styleguidist/lib/client/utils/renderStyleguide.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/renderStyleguide'>;
}
declare module 'react-styleguidist/lib/client/utils/rewriteImports.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/rewriteImports'>;
}
declare module 'react-styleguidist/lib/client/utils/splitExampleCode.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/splitExampleCode'>;
}
declare module 'react-styleguidist/lib/client/utils/transpileImports.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/client/utils/transpileImports'>;
}
declare module 'react-styleguidist/lib/loaders/examples-loader.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/examples-loader'>;
}
declare module 'react-styleguidist/lib/loaders/props-loader.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/props-loader'>;
}
declare module 'react-styleguidist/lib/loaders/styleguide-loader.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/styleguide-loader'>;
}
declare module 'react-styleguidist/lib/loaders/utils/chunkify.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/chunkify'>;
}
declare module 'react-styleguidist/lib/loaders/utils/client/evalInContext.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/client/evalInContext'>;
}
declare module 'react-styleguidist/lib/loaders/utils/client/requireInRuntime.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/client/requireInRuntime'>;
}
declare module 'react-styleguidist/lib/loaders/utils/expandDefaultComponent.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/expandDefaultComponent'>;
}
declare module 'react-styleguidist/lib/loaders/utils/filterComponentsWithExample.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/filterComponentsWithExample'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getAllContentPages.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getAllContentPages'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getAst.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getAst'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getComponentFiles.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getComponentFiles'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getComponentFilesFromSections.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getComponentFilesFromSections'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getComponentPatternsFromSections.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getComponentPatternsFromSections'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getComponents.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getComponents'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getExamples.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getExamples'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getImports.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getImports'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getNameFromFilePath.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getNameFromFilePath'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getProps.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getProps'>;
}
declare module 'react-styleguidist/lib/loaders/utils/getSections.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/getSections'>;
}
declare module 'react-styleguidist/lib/loaders/utils/highlightCode.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/highlightCode'>;
}
declare module 'react-styleguidist/lib/loaders/utils/highlightCodeInMarkdown.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/highlightCodeInMarkdown'>;
}
declare module 'react-styleguidist/lib/loaders/utils/noAutoLinkRemarkPlugin.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/noAutoLinkRemarkPlugin'>;
}
declare module 'react-styleguidist/lib/loaders/utils/parseExample.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/parseExample'>;
}
declare module 'react-styleguidist/lib/loaders/utils/processComponent.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/processComponent'>;
}
declare module 'react-styleguidist/lib/loaders/utils/removeDoclets.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/removeDoclets'>;
}
declare module 'react-styleguidist/lib/loaders/utils/requireIt.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/requireIt'>;
}
declare module 'react-styleguidist/lib/loaders/utils/slugger.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/slugger'>;
}
declare module 'react-styleguidist/lib/loaders/utils/sortProps.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/loaders/utils/sortProps'>;
}
declare module 'react-styleguidist/lib/scripts/__mocks__/build.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/__mocks__/build'>;
}
declare module 'react-styleguidist/lib/scripts/__mocks__/server.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/__mocks__/server'>;
}
declare module 'react-styleguidist/lib/scripts/build.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/build'>;
}
declare module 'react-styleguidist/lib/scripts/config.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/config'>;
}
declare module 'react-styleguidist/lib/scripts/consts.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/consts'>;
}
declare module 'react-styleguidist/lib/scripts/create-server.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/create-server'>;
}
declare module 'react-styleguidist/lib/scripts/index.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/index'>;
}
declare module 'react-styleguidist/lib/scripts/logger.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/logger'>;
}
declare module 'react-styleguidist/lib/scripts/make-webpack-config.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/make-webpack-config'>;
}
declare module 'react-styleguidist/lib/scripts/schemas/config.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/schemas/config'>;
}
declare module 'react-styleguidist/lib/scripts/server.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/server'>;
}
declare module 'react-styleguidist/lib/scripts/utils/ensureWebpack.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/ensureWebpack'>;
}
declare module 'react-styleguidist/lib/scripts/utils/error.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/error'>;
}
declare module 'react-styleguidist/lib/scripts/utils/findFileCaseInsensitive.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/findFileCaseInsensitive'>;
}
declare module 'react-styleguidist/lib/scripts/utils/findUserWebpackConfig.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/findUserWebpackConfig'>;
}
declare module 'react-styleguidist/lib/scripts/utils/getUserPackageJson.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/getUserPackageJson'>;
}
declare module 'react-styleguidist/lib/scripts/utils/getWebpackVersion.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/getWebpackVersion'>;
}
declare module 'react-styleguidist/lib/scripts/utils/mergeWebpackConfig.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/mergeWebpackConfig'>;
}
declare module 'react-styleguidist/lib/scripts/utils/sanitizeConfig.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/sanitizeConfig'>;
}
declare module 'react-styleguidist/lib/scripts/utils/StyleguidistOptionsPlugin.js' {
  declare module.exports: $Exports<'react-styleguidist/lib/scripts/utils/StyleguidistOptionsPlugin'>;
}
