// flow-typed signature: cd498f53becdf910ac439b08371527a7
// flow-typed version: <<STUB>>/react-cropper_v^2.1.4/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-cropper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-cropper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-cropper/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'react-cropper/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-cropper/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-cropper/dist/react-cropper.es' {
  declare module.exports: any;
}

declare module 'react-cropper/dist/react-cropper.umd' {
  declare module.exports: any;
}

declare module 'react-cropper/jest.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-cropper/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'react-cropper/coverage/lcov-report/block-navigation'>;
}
declare module 'react-cropper/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-cropper/coverage/lcov-report/prettify'>;
}
declare module 'react-cropper/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-cropper/coverage/lcov-report/sorter'>;
}
declare module 'react-cropper/dist/react-cropper.es.js' {
  declare module.exports: $Exports<'react-cropper/dist/react-cropper.es'>;
}
declare module 'react-cropper/dist/react-cropper.umd.js' {
  declare module.exports: $Exports<'react-cropper/dist/react-cropper.umd'>;
}
declare module 'react-cropper/jest.config.js' {
  declare module.exports: $Exports<'react-cropper/jest.config'>;
}
