// flow-typed signature: 1214b185feb491fbc9ed80e9d8360b83
// flow-typed version: <<STUB>>/react-youtube_v^7.9.0/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-youtube'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-youtube' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-youtube/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-youtube/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-youtube/dist/index.esm.js' {
  declare module.exports: $Exports<'react-youtube/dist/index.esm'>;
}
declare module 'react-youtube/dist/index' {
  declare module.exports: $Exports<'react-youtube/dist'>;
}
declare module 'react-youtube/dist/index.js' {
  declare module.exports: $Exports<'react-youtube/dist'>;
}
