// flow-typed signature: 2293859c467f3ff9a8f343d76c5dca16
// flow-typed version: <<STUB>>/react-google-recaptcha_v^1.0.5/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-recaptcha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-recaptcha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-recaptcha/jest.config' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/es/index' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/es/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/es/recaptcha' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/index' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/recaptcha' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src/index' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src/recaptcha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-recaptcha/jest.config.js' {
  declare module.exports: $Exports<'react-google-recaptcha/jest.config'>;
}
declare module 'react-google-recaptcha/lib/es/index.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/es/index'>;
}
declare module 'react-google-recaptcha/lib/es/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/es/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/lib/es/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/es/recaptcha'>;
}
declare module 'react-google-recaptcha/lib/index.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/index'>;
}
declare module 'react-google-recaptcha/lib/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/lib/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/recaptcha'>;
}
declare module 'react-google-recaptcha/src/index.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src/index'>;
}
declare module 'react-google-recaptcha/src/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/src/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src/recaptcha'>;
}
