// flow-typed signature: bf6720b6c38a579f714fd0464dda6c8c
// flow-typed version: <<STUB>>/react-prepare_v^0.4.0/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-prepare'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-prepare' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-prepare/dist/constants' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/dispatched' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/index' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/prepare' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/prepared' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/tests/dispatched.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/tests/isReactCompositeComponent.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/tests/isThenable.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/tests/prepare.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/tests/prepared.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/tests/ReactLifeCycle.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/utils/isReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-prepare/dist/utils/isThenable' {
  declare module.exports: any;
}

declare module 'react-prepare/src/constants' {
  declare module.exports: any;
}

declare module 'react-prepare/src/dispatched' {
  declare module.exports: any;
}

declare module 'react-prepare/src/index' {
  declare module.exports: any;
}

declare module 'react-prepare/src/prepare' {
  declare module.exports: any;
}

declare module 'react-prepare/src/prepared' {
  declare module.exports: any;
}

declare module 'react-prepare/src/tests/dispatched.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/src/tests/isReactCompositeComponent.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/src/tests/isThenable.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/src/tests/prepare.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/src/tests/prepared.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/src/tests/ReactLifeCycle.spec' {
  declare module.exports: any;
}

declare module 'react-prepare/src/utils/isReactCompositeComponent' {
  declare module.exports: any;
}

declare module 'react-prepare/src/utils/isThenable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-prepare/dist/constants.js' {
  declare module.exports: $Exports<'react-prepare/dist/constants'>;
}
declare module 'react-prepare/dist/dispatched.js' {
  declare module.exports: $Exports<'react-prepare/dist/dispatched'>;
}
declare module 'react-prepare/dist/index.js' {
  declare module.exports: $Exports<'react-prepare/dist/index'>;
}
declare module 'react-prepare/dist/prepare.js' {
  declare module.exports: $Exports<'react-prepare/dist/prepare'>;
}
declare module 'react-prepare/dist/prepared.js' {
  declare module.exports: $Exports<'react-prepare/dist/prepared'>;
}
declare module 'react-prepare/dist/tests/dispatched.spec.js' {
  declare module.exports: $Exports<'react-prepare/dist/tests/dispatched.spec'>;
}
declare module 'react-prepare/dist/tests/isReactCompositeComponent.spec.js' {
  declare module.exports: $Exports<'react-prepare/dist/tests/isReactCompositeComponent.spec'>;
}
declare module 'react-prepare/dist/tests/isThenable.spec.js' {
  declare module.exports: $Exports<'react-prepare/dist/tests/isThenable.spec'>;
}
declare module 'react-prepare/dist/tests/prepare.spec.js' {
  declare module.exports: $Exports<'react-prepare/dist/tests/prepare.spec'>;
}
declare module 'react-prepare/dist/tests/prepared.spec.js' {
  declare module.exports: $Exports<'react-prepare/dist/tests/prepared.spec'>;
}
declare module 'react-prepare/dist/tests/ReactLifeCycle.spec.js' {
  declare module.exports: $Exports<'react-prepare/dist/tests/ReactLifeCycle.spec'>;
}
declare module 'react-prepare/dist/utils/isReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-prepare/dist/utils/isReactCompositeComponent'>;
}
declare module 'react-prepare/dist/utils/isThenable.js' {
  declare module.exports: $Exports<'react-prepare/dist/utils/isThenable'>;
}
declare module 'react-prepare/src/constants.js' {
  declare module.exports: $Exports<'react-prepare/src/constants'>;
}
declare module 'react-prepare/src/dispatched.js' {
  declare module.exports: $Exports<'react-prepare/src/dispatched'>;
}
declare module 'react-prepare/src/index.js' {
  declare module.exports: $Exports<'react-prepare/src/index'>;
}
declare module 'react-prepare/src/prepare.js' {
  declare module.exports: $Exports<'react-prepare/src/prepare'>;
}
declare module 'react-prepare/src/prepared.js' {
  declare module.exports: $Exports<'react-prepare/src/prepared'>;
}
declare module 'react-prepare/src/tests/dispatched.spec.js' {
  declare module.exports: $Exports<'react-prepare/src/tests/dispatched.spec'>;
}
declare module 'react-prepare/src/tests/isReactCompositeComponent.spec.js' {
  declare module.exports: $Exports<'react-prepare/src/tests/isReactCompositeComponent.spec'>;
}
declare module 'react-prepare/src/tests/isThenable.spec.js' {
  declare module.exports: $Exports<'react-prepare/src/tests/isThenable.spec'>;
}
declare module 'react-prepare/src/tests/prepare.spec.js' {
  declare module.exports: $Exports<'react-prepare/src/tests/prepare.spec'>;
}
declare module 'react-prepare/src/tests/prepared.spec.js' {
  declare module.exports: $Exports<'react-prepare/src/tests/prepared.spec'>;
}
declare module 'react-prepare/src/tests/ReactLifeCycle.spec.js' {
  declare module.exports: $Exports<'react-prepare/src/tests/ReactLifeCycle.spec'>;
}
declare module 'react-prepare/src/utils/isReactCompositeComponent.js' {
  declare module.exports: $Exports<'react-prepare/src/utils/isReactCompositeComponent'>;
}
declare module 'react-prepare/src/utils/isThenable.js' {
  declare module.exports: $Exports<'react-prepare/src/utils/isThenable'>;
}
