// flow-typed signature: 4a4b2729f4d51f67cb36c49223594d05
// flow-typed version: <<STUB>>/react-treeview_v^0.4.6/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-treeview'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-treeview' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-treeview/lib/react-treeview' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-treeview/lib/react-treeview.js' {
  declare module.exports: $Exports<'react-treeview/lib/react-treeview'>;
}
