// flow-typed signature: 2753f514886a662d8a9485c51f8dcd8a
// flow-typed version: <<STUB>>/react-google-recaptcha_v^0.5.4/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-google-recaptcha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-google-recaptcha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-google-recaptcha/lib/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/lib/recaptcha' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src/recaptcha-wrapper' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/src/recaptcha' {
  declare module.exports: any;
}

declare module 'react-google-recaptcha/webpack.config.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-google-recaptcha/lib/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/lib/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/lib/recaptcha'>;
}
declare module 'react-google-recaptcha/src/recaptcha-wrapper.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src/recaptcha-wrapper'>;
}
declare module 'react-google-recaptcha/src/recaptcha.js' {
  declare module.exports: $Exports<'react-google-recaptcha/src/recaptcha'>;
}
declare module 'react-google-recaptcha/webpack.config.test.js' {
  declare module.exports: $Exports<'react-google-recaptcha/webpack.config.test'>;
}
