// flow-typed signature: d8da6dd5f53cdb7204591c5d3185f10f
// flow-typed version: <<STUB>>/react-swipeable_v5.5.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-swipeable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-swipeable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-swipeable/es' {
  declare module.exports: any;
}

declare module 'react-swipeable/lib' {
  declare module.exports: any;
}

declare module 'react-swipeable/src/__mocks__/react' {
  declare module.exports: any;
}

declare module 'react-swipeable/src/__tests__/helpers/events' {
  declare module.exports: any;
}

declare module 'react-swipeable/src/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'react-swipeable/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-swipeable/es/index' {
  declare module.exports: $Exports<'react-swipeable/es'>;
}
declare module 'react-swipeable/es/index.js' {
  declare module.exports: $Exports<'react-swipeable/es'>;
}
declare module 'react-swipeable/lib/index' {
  declare module.exports: $Exports<'react-swipeable/lib'>;
}
declare module 'react-swipeable/lib/index.js' {
  declare module.exports: $Exports<'react-swipeable/lib'>;
}
declare module 'react-swipeable/src/__mocks__/react.js' {
  declare module.exports: $Exports<'react-swipeable/src/__mocks__/react'>;
}
declare module 'react-swipeable/src/__tests__/helpers/events.js' {
  declare module.exports: $Exports<'react-swipeable/src/__tests__/helpers/events'>;
}
declare module 'react-swipeable/src/__tests__/index.spec.js' {
  declare module.exports: $Exports<'react-swipeable/src/__tests__/index.spec'>;
}
declare module 'react-swipeable/src/index' {
  declare module.exports: $Exports<'react-swipeable/src'>;
}
declare module 'react-swipeable/src/index.js' {
  declare module.exports: $Exports<'react-swipeable/src'>;
}
