// flow-typed signature: 7f0a87805f56fec52fcc075d7041cdee
// flow-typed version: <<STUB>>/react-soundplayer_v^1.0.4/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-soundplayer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-soundplayer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-soundplayer/addons' {
  declare module.exports: any;
}

declare module 'react-soundplayer/components' {
  declare module.exports: any;
}

declare module 'react-soundplayer/dist/react-soundplayer' {
  declare module.exports: any;
}

declare module 'react-soundplayer/dist/react-soundplayer.min' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/addons/index' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/addons/SoundPlayerContainer' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/addons/withSoundCloudAudio' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/Cover' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/Icons' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/index' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/NextButton' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/PlayButton' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/PrevButton' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/Progress' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/Timer' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/components/VolumeControl' {
  declare module.exports: any;
}

declare module 'react-soundplayer/lib/utils/audioStore' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/addons/index' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/addons/SoundPlayerContainer' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/addons/withSoundCloudAudio' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/Cover' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/Icons' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/index' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/NextButton' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/PlayButton' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/PrevButton' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/Progress' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/Timer' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/components/VolumeControl' {
  declare module.exports: any;
}

declare module 'react-soundplayer/src/utils/audioStore' {
  declare module.exports: any;
}

declare module 'react-soundplayer/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-soundplayer/addons.js' {
  declare module.exports: $Exports<'react-soundplayer/addons'>;
}
declare module 'react-soundplayer/components.js' {
  declare module.exports: $Exports<'react-soundplayer/components'>;
}
declare module 'react-soundplayer/dist/react-soundplayer.js' {
  declare module.exports: $Exports<'react-soundplayer/dist/react-soundplayer'>;
}
declare module 'react-soundplayer/dist/react-soundplayer.min.js' {
  declare module.exports: $Exports<'react-soundplayer/dist/react-soundplayer.min'>;
}
declare module 'react-soundplayer/index' {
  declare module.exports: $Exports<'react-soundplayer'>;
}
declare module 'react-soundplayer/index.js' {
  declare module.exports: $Exports<'react-soundplayer'>;
}
declare module 'react-soundplayer/lib/addons/index.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/addons/index'>;
}
declare module 'react-soundplayer/lib/addons/SoundPlayerContainer.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/addons/SoundPlayerContainer'>;
}
declare module 'react-soundplayer/lib/addons/withSoundCloudAudio.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/addons/withSoundCloudAudio'>;
}
declare module 'react-soundplayer/lib/components/Cover.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/Cover'>;
}
declare module 'react-soundplayer/lib/components/Icons.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/Icons'>;
}
declare module 'react-soundplayer/lib/components/index.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/index'>;
}
declare module 'react-soundplayer/lib/components/NextButton.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/NextButton'>;
}
declare module 'react-soundplayer/lib/components/PlayButton.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/PlayButton'>;
}
declare module 'react-soundplayer/lib/components/PrevButton.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/PrevButton'>;
}
declare module 'react-soundplayer/lib/components/Progress.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/Progress'>;
}
declare module 'react-soundplayer/lib/components/Timer.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/Timer'>;
}
declare module 'react-soundplayer/lib/components/VolumeControl.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/components/VolumeControl'>;
}
declare module 'react-soundplayer/lib/utils/audioStore.js' {
  declare module.exports: $Exports<'react-soundplayer/lib/utils/audioStore'>;
}
declare module 'react-soundplayer/src/addons/index.js' {
  declare module.exports: $Exports<'react-soundplayer/src/addons/index'>;
}
declare module 'react-soundplayer/src/addons/SoundPlayerContainer.js' {
  declare module.exports: $Exports<'react-soundplayer/src/addons/SoundPlayerContainer'>;
}
declare module 'react-soundplayer/src/addons/withSoundCloudAudio.js' {
  declare module.exports: $Exports<'react-soundplayer/src/addons/withSoundCloudAudio'>;
}
declare module 'react-soundplayer/src/components/Cover.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/Cover'>;
}
declare module 'react-soundplayer/src/components/Icons.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/Icons'>;
}
declare module 'react-soundplayer/src/components/index.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/index'>;
}
declare module 'react-soundplayer/src/components/NextButton.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/NextButton'>;
}
declare module 'react-soundplayer/src/components/PlayButton.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/PlayButton'>;
}
declare module 'react-soundplayer/src/components/PrevButton.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/PrevButton'>;
}
declare module 'react-soundplayer/src/components/Progress.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/Progress'>;
}
declare module 'react-soundplayer/src/components/Timer.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/Timer'>;
}
declare module 'react-soundplayer/src/components/VolumeControl.js' {
  declare module.exports: $Exports<'react-soundplayer/src/components/VolumeControl'>;
}
declare module 'react-soundplayer/src/utils/audioStore.js' {
  declare module.exports: $Exports<'react-soundplayer/src/utils/audioStore'>;
}
declare module 'react-soundplayer/webpack.config.js' {
  declare module.exports: $Exports<'react-soundplayer/webpack.config'>;
}
