// flow-typed signature: a9ed7f74552a993e1b34580bc41751f1
// flow-typed version: <<STUB>>/react-collapse_v^4.0.3/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-collapse'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-collapse' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-collapse/build/react-collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/build/react-collapse.min' {
  declare module.exports: any;
}

declare module 'react-collapse/lib/Collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/lib/index' {
  declare module.exports: any;
}

declare module 'react-collapse/lib/UnmountClosed' {
  declare module.exports: any;
}

declare module 'react-collapse/src/Collapse' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/AutoUnmount' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/FixedHeight' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/Hooks' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/index' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/InitiallyOpened' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/Issue163' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/Issue40' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/Issue59' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/Issue66' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/Nested' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/SpringConfig' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/VariableHeight' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/App/VariableText' {
  declare module.exports: any;
}

declare module 'react-collapse/src/example/Example' {
  declare module.exports: any;
}

declare module 'react-collapse/src/index' {
  declare module.exports: any;
}

declare module 'react-collapse/src/UnmountClosed' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-collapse/build/react-collapse.js' {
  declare module.exports: $Exports<'react-collapse/build/react-collapse'>;
}
declare module 'react-collapse/build/react-collapse.min.js' {
  declare module.exports: $Exports<'react-collapse/build/react-collapse.min'>;
}
declare module 'react-collapse/lib/Collapse.js' {
  declare module.exports: $Exports<'react-collapse/lib/Collapse'>;
}
declare module 'react-collapse/lib/index.js' {
  declare module.exports: $Exports<'react-collapse/lib/index'>;
}
declare module 'react-collapse/lib/UnmountClosed.js' {
  declare module.exports: $Exports<'react-collapse/lib/UnmountClosed'>;
}
declare module 'react-collapse/src/Collapse.js' {
  declare module.exports: $Exports<'react-collapse/src/Collapse'>;
}
declare module 'react-collapse/src/example/App/AutoUnmount.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/AutoUnmount'>;
}
declare module 'react-collapse/src/example/App/FixedHeight.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/FixedHeight'>;
}
declare module 'react-collapse/src/example/App/Hooks.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/Hooks'>;
}
declare module 'react-collapse/src/example/App/index.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/index'>;
}
declare module 'react-collapse/src/example/App/InitiallyOpened.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/InitiallyOpened'>;
}
declare module 'react-collapse/src/example/App/Issue163.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/Issue163'>;
}
declare module 'react-collapse/src/example/App/Issue40.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/Issue40'>;
}
declare module 'react-collapse/src/example/App/Issue59.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/Issue59'>;
}
declare module 'react-collapse/src/example/App/Issue66.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/Issue66'>;
}
declare module 'react-collapse/src/example/App/Nested.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/Nested'>;
}
declare module 'react-collapse/src/example/App/SpringConfig.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/SpringConfig'>;
}
declare module 'react-collapse/src/example/App/VariableHeight.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/VariableHeight'>;
}
declare module 'react-collapse/src/example/App/VariableText.js' {
  declare module.exports: $Exports<'react-collapse/src/example/App/VariableText'>;
}
declare module 'react-collapse/src/example/Example.js' {
  declare module.exports: $Exports<'react-collapse/src/example/Example'>;
}
declare module 'react-collapse/src/index.js' {
  declare module.exports: $Exports<'react-collapse/src/index'>;
}
declare module 'react-collapse/src/UnmountClosed.js' {
  declare module.exports: $Exports<'react-collapse/src/UnmountClosed'>;
}
