// flow-typed signature: 5ce199fee14d343ca6c39554dcb3667e
// flow-typed version: <<STUB>>/redux-segment_v^1.6.2/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-segment'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-segment' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-segment/dist/event/alias' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/event/configuration' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/event/group' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/event/identify' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/event/page' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/event/track' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/event/types' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/index' {
  declare module.exports: any;
}

declare module 'redux-segment/dist/utils' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/angular2-redux/e2e/login.spec' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/angular2-redux/e2e/selectors' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/angular2-redux/gulpfile' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/angular2-redux/karma.conf' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/angular2-redux/server' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/angular2-redux/wdio.conf' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/angular2-redux/webpack.config' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/server' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/actions/counter' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/actions/session' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/api/login' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/counter/Counter' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/login/LoginForm' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/login/LoginModal' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/navigator/Navigator' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/navigator/NavigatorItem' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Alert' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Button' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Column' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Container' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Content' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Form' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/FormError' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/FormGroup' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/FormLabel' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Input' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Input.test' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Logo' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Modal' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/Modal.test' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/components/ui/ModalContent' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/constants/index' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/containers/AboutPage' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/containers/App' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/containers/CounterPage' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/index' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/middleware/promiseMiddleware' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/reducers/counter' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/reducers/counter.test' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/reducers/index' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/reducers/session' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/reducers/session.test' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/store/configureStore' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/store/logger' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/store/routes' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/utils/fireAction' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/utils/fireAction.test' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/utils/immutableToJS' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/utils/immutableToJS.test' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/utils/isPromise' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/src/utils/isPromise.test' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/test/entry' {
  declare module.exports: any;
}

declare module 'redux-segment/examples/react-redux/webpack.config' {
  declare module.exports: any;
}

declare module 'redux-segment/src/event/alias' {
  declare module.exports: any;
}

declare module 'redux-segment/src/event/configuration' {
  declare module.exports: any;
}

declare module 'redux-segment/src/event/group' {
  declare module.exports: any;
}

declare module 'redux-segment/src/event/identify' {
  declare module.exports: any;
}

declare module 'redux-segment/src/event/page' {
  declare module.exports: any;
}

declare module 'redux-segment/src/event/track' {
  declare module.exports: any;
}

declare module 'redux-segment/src/event/types' {
  declare module.exports: any;
}

declare module 'redux-segment/src/index' {
  declare module.exports: any;
}

declare module 'redux-segment/src/utils' {
  declare module.exports: any;
}

declare module 'redux-segment/test/alias-test' {
  declare module.exports: any;
}

declare module 'redux-segment/test/group-test' {
  declare module.exports: any;
}

declare module 'redux-segment/test/helpers/console-stub' {
  declare module.exports: any;
}

declare module 'redux-segment/test/helpers/env-setup' {
  declare module.exports: any;
}

declare module 'redux-segment/test/helpers/segment-stub' {
  declare module.exports: any;
}

declare module 'redux-segment/test/helpers/test-setup' {
  declare module.exports: any;
}

declare module 'redux-segment/test/identify-test' {
  declare module.exports: any;
}

declare module 'redux-segment/test/ngrx-track-test' {
  declare module.exports: any;
}

declare module 'redux-segment/test/page-test' {
  declare module.exports: any;
}

declare module 'redux-segment/test/reset-test' {
  declare module.exports: any;
}

declare module 'redux-segment/test/track-test' {
  declare module.exports: any;
}

declare module 'redux-segment/typings/redux-segment-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-segment/dist/event/alias.js' {
  declare module.exports: $Exports<'redux-segment/dist/event/alias'>;
}
declare module 'redux-segment/dist/event/configuration.js' {
  declare module.exports: $Exports<'redux-segment/dist/event/configuration'>;
}
declare module 'redux-segment/dist/event/group.js' {
  declare module.exports: $Exports<'redux-segment/dist/event/group'>;
}
declare module 'redux-segment/dist/event/identify.js' {
  declare module.exports: $Exports<'redux-segment/dist/event/identify'>;
}
declare module 'redux-segment/dist/event/page.js' {
  declare module.exports: $Exports<'redux-segment/dist/event/page'>;
}
declare module 'redux-segment/dist/event/track.js' {
  declare module.exports: $Exports<'redux-segment/dist/event/track'>;
}
declare module 'redux-segment/dist/event/types.js' {
  declare module.exports: $Exports<'redux-segment/dist/event/types'>;
}
declare module 'redux-segment/dist/index.js' {
  declare module.exports: $Exports<'redux-segment/dist/index'>;
}
declare module 'redux-segment/dist/utils.js' {
  declare module.exports: $Exports<'redux-segment/dist/utils'>;
}
declare module 'redux-segment/examples/angular2-redux/e2e/login.spec.js' {
  declare module.exports: $Exports<'redux-segment/examples/angular2-redux/e2e/login.spec'>;
}
declare module 'redux-segment/examples/angular2-redux/e2e/selectors.js' {
  declare module.exports: $Exports<'redux-segment/examples/angular2-redux/e2e/selectors'>;
}
declare module 'redux-segment/examples/angular2-redux/gulpfile.js' {
  declare module.exports: $Exports<'redux-segment/examples/angular2-redux/gulpfile'>;
}
declare module 'redux-segment/examples/angular2-redux/karma.conf.js' {
  declare module.exports: $Exports<'redux-segment/examples/angular2-redux/karma.conf'>;
}
declare module 'redux-segment/examples/angular2-redux/server.js' {
  declare module.exports: $Exports<'redux-segment/examples/angular2-redux/server'>;
}
declare module 'redux-segment/examples/angular2-redux/wdio.conf.js' {
  declare module.exports: $Exports<'redux-segment/examples/angular2-redux/wdio.conf'>;
}
declare module 'redux-segment/examples/angular2-redux/webpack.config.js' {
  declare module.exports: $Exports<'redux-segment/examples/angular2-redux/webpack.config'>;
}
declare module 'redux-segment/examples/react-redux/server.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/server'>;
}
declare module 'redux-segment/examples/react-redux/src/actions/counter.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/actions/counter'>;
}
declare module 'redux-segment/examples/react-redux/src/actions/session.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/actions/session'>;
}
declare module 'redux-segment/examples/react-redux/src/api/login.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/api/login'>;
}
declare module 'redux-segment/examples/react-redux/src/components/counter/Counter.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/counter/Counter'>;
}
declare module 'redux-segment/examples/react-redux/src/components/login/LoginForm.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/login/LoginForm'>;
}
declare module 'redux-segment/examples/react-redux/src/components/login/LoginModal.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/login/LoginModal'>;
}
declare module 'redux-segment/examples/react-redux/src/components/navigator/Navigator.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/navigator/Navigator'>;
}
declare module 'redux-segment/examples/react-redux/src/components/navigator/NavigatorItem.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/navigator/NavigatorItem'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Alert.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Alert'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Button.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Button'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Column.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Column'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Container.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Container'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Content.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Content'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Form.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Form'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/FormError.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/FormError'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/FormGroup.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/FormGroup'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/FormLabel.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/FormLabel'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Input.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Input'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Input.test.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Input.test'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Logo.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Logo'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Modal.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Modal'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/Modal.test.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/Modal.test'>;
}
declare module 'redux-segment/examples/react-redux/src/components/ui/ModalContent.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/components/ui/ModalContent'>;
}
declare module 'redux-segment/examples/react-redux/src/constants/index.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/constants/index'>;
}
declare module 'redux-segment/examples/react-redux/src/containers/AboutPage.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/containers/AboutPage'>;
}
declare module 'redux-segment/examples/react-redux/src/containers/App.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/containers/App'>;
}
declare module 'redux-segment/examples/react-redux/src/containers/CounterPage.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/containers/CounterPage'>;
}
declare module 'redux-segment/examples/react-redux/src/index.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/index'>;
}
declare module 'redux-segment/examples/react-redux/src/middleware/promiseMiddleware.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/middleware/promiseMiddleware'>;
}
declare module 'redux-segment/examples/react-redux/src/reducers/counter.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/reducers/counter'>;
}
declare module 'redux-segment/examples/react-redux/src/reducers/counter.test.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/reducers/counter.test'>;
}
declare module 'redux-segment/examples/react-redux/src/reducers/index.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/reducers/index'>;
}
declare module 'redux-segment/examples/react-redux/src/reducers/session.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/reducers/session'>;
}
declare module 'redux-segment/examples/react-redux/src/reducers/session.test.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/reducers/session.test'>;
}
declare module 'redux-segment/examples/react-redux/src/store/configureStore.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/store/configureStore'>;
}
declare module 'redux-segment/examples/react-redux/src/store/logger.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/store/logger'>;
}
declare module 'redux-segment/examples/react-redux/src/store/routes.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/store/routes'>;
}
declare module 'redux-segment/examples/react-redux/src/utils/fireAction.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/utils/fireAction'>;
}
declare module 'redux-segment/examples/react-redux/src/utils/fireAction.test.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/utils/fireAction.test'>;
}
declare module 'redux-segment/examples/react-redux/src/utils/immutableToJS.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/utils/immutableToJS'>;
}
declare module 'redux-segment/examples/react-redux/src/utils/immutableToJS.test.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/utils/immutableToJS.test'>;
}
declare module 'redux-segment/examples/react-redux/src/utils/isPromise.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/utils/isPromise'>;
}
declare module 'redux-segment/examples/react-redux/src/utils/isPromise.test.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/src/utils/isPromise.test'>;
}
declare module 'redux-segment/examples/react-redux/test/entry.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/test/entry'>;
}
declare module 'redux-segment/examples/react-redux/webpack.config.js' {
  declare module.exports: $Exports<'redux-segment/examples/react-redux/webpack.config'>;
}
declare module 'redux-segment/src/event/alias.js' {
  declare module.exports: $Exports<'redux-segment/src/event/alias'>;
}
declare module 'redux-segment/src/event/configuration.js' {
  declare module.exports: $Exports<'redux-segment/src/event/configuration'>;
}
declare module 'redux-segment/src/event/group.js' {
  declare module.exports: $Exports<'redux-segment/src/event/group'>;
}
declare module 'redux-segment/src/event/identify.js' {
  declare module.exports: $Exports<'redux-segment/src/event/identify'>;
}
declare module 'redux-segment/src/event/page.js' {
  declare module.exports: $Exports<'redux-segment/src/event/page'>;
}
declare module 'redux-segment/src/event/track.js' {
  declare module.exports: $Exports<'redux-segment/src/event/track'>;
}
declare module 'redux-segment/src/event/types.js' {
  declare module.exports: $Exports<'redux-segment/src/event/types'>;
}
declare module 'redux-segment/src/index.js' {
  declare module.exports: $Exports<'redux-segment/src/index'>;
}
declare module 'redux-segment/src/utils.js' {
  declare module.exports: $Exports<'redux-segment/src/utils'>;
}
declare module 'redux-segment/test/alias-test.js' {
  declare module.exports: $Exports<'redux-segment/test/alias-test'>;
}
declare module 'redux-segment/test/group-test.js' {
  declare module.exports: $Exports<'redux-segment/test/group-test'>;
}
declare module 'redux-segment/test/helpers/console-stub.js' {
  declare module.exports: $Exports<'redux-segment/test/helpers/console-stub'>;
}
declare module 'redux-segment/test/helpers/env-setup.js' {
  declare module.exports: $Exports<'redux-segment/test/helpers/env-setup'>;
}
declare module 'redux-segment/test/helpers/segment-stub.js' {
  declare module.exports: $Exports<'redux-segment/test/helpers/segment-stub'>;
}
declare module 'redux-segment/test/helpers/test-setup.js' {
  declare module.exports: $Exports<'redux-segment/test/helpers/test-setup'>;
}
declare module 'redux-segment/test/identify-test.js' {
  declare module.exports: $Exports<'redux-segment/test/identify-test'>;
}
declare module 'redux-segment/test/ngrx-track-test.js' {
  declare module.exports: $Exports<'redux-segment/test/ngrx-track-test'>;
}
declare module 'redux-segment/test/page-test.js' {
  declare module.exports: $Exports<'redux-segment/test/page-test'>;
}
declare module 'redux-segment/test/reset-test.js' {
  declare module.exports: $Exports<'redux-segment/test/reset-test'>;
}
declare module 'redux-segment/test/track-test.js' {
  declare module.exports: $Exports<'redux-segment/test/track-test'>;
}
declare module 'redux-segment/typings/redux-segment-tests.js' {
  declare module.exports: $Exports<'redux-segment/typings/redux-segment-tests'>;
}
