// flow-typed signature: 77bab381cdcba0febd26e97d638d2ebb
// flow-typed version: <<STUB>>/redux-sentry-middleware_v^0.1.8/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-sentry-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-sentry-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-sentry-middleware/dist/index.cjs' {
  declare module.exports: any;
}

declare module 'redux-sentry-middleware/dist/index.esm' {
  declare module.exports: any;
}

declare module 'redux-sentry-middleware/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-sentry-middleware/dist/index.cjs.js' {
  declare module.exports: $Exports<'redux-sentry-middleware/dist/index.cjs'>;
}
declare module 'redux-sentry-middleware/dist/index.esm.js' {
  declare module.exports: $Exports<'redux-sentry-middleware/dist/index.esm'>;
}
declare module 'redux-sentry-middleware/dist/index.umd.js' {
  declare module.exports: $Exports<'redux-sentry-middleware/dist/index.umd'>;
}
