// flow-typed signature: de1604c270a9108be9b470102e858639
// flow-typed version: <<STUB>>/slate-auto-replace_v0.6.2/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-auto-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-auto-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-auto-replace/dist/slate-auto-replace' {
  declare module.exports: any;
}

declare module 'slate-auto-replace/dist/slate-auto-replace.min' {
  declare module.exports: any;
}

declare module 'slate-auto-replace/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-auto-replace/dist/slate-auto-replace.js' {
  declare module.exports: $Exports<'slate-auto-replace/dist/slate-auto-replace'>;
}
declare module 'slate-auto-replace/dist/slate-auto-replace.min.js' {
  declare module.exports: $Exports<'slate-auto-replace/dist/slate-auto-replace.min'>;
}
declare module 'slate-auto-replace/lib/index.js' {
  declare module.exports: $Exports<'slate-auto-replace/lib/index'>;
}
