// flow-typed signature: a613164e779e85f033c5c9e6ce8f1cf2
// flow-typed version: <<STUB>>/slate-auto-replace_v^0.3.0/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-auto-replace'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-auto-replace' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-auto-replace/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-auto-replace/dist/index.js' {
  declare module.exports: $Exports<'slate-auto-replace/dist/index'>;
}
