// flow-typed signature: 0424624baf12365977d50374d6fb720f
// flow-typed version: <<STUB>>/slate-auto-replace-text_v^0.3.1/flow_v0.45.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-auto-replace-text'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-auto-replace-text' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-auto-replace-text/dist/index' {
  declare module.exports: any;
}

declare module 'slate-auto-replace-text/example/build' {
  declare module.exports: any;
}

declare module 'slate-auto-replace-text/example/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-auto-replace-text/dist/index.js' {
  declare module.exports: $Exports<'slate-auto-replace-text/dist/index'>;
}
declare module 'slate-auto-replace-text/example/build.js' {
  declare module.exports: $Exports<'slate-auto-replace-text/example/build'>;
}
declare module 'slate-auto-replace-text/example/index.js' {
  declare module.exports: $Exports<'slate-auto-replace-text/example/index'>;
}
