// flow-typed signature: 74f513a6c1b240dc70dbf47c633237e1
// flow-typed version: <<STUB>>/slate-html-serializer_v^0.1.5/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-html-serializer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-html-serializer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-html-serializer/dist/slate-html-serializer' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/dist/slate-html-serializer.min' {
  declare module.exports: any;
}

declare module 'slate-html-serializer/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-html-serializer/dist/slate-html-serializer.js' {
  declare module.exports: $Exports<'slate-html-serializer/dist/slate-html-serializer'>;
}
declare module 'slate-html-serializer/dist/slate-html-serializer.min.js' {
  declare module.exports: $Exports<'slate-html-serializer/dist/slate-html-serializer.min'>;
}
declare module 'slate-html-serializer/lib/index.js' {
  declare module.exports: $Exports<'slate-html-serializer/lib/index'>;
}
