// flow-typed signature: ca6269e54c69c191d3a177ad4889f3f4
// flow-typed version: <<STUB>>/slate-react_v^0.1.5/flow_v0.57.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'slate-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'slate-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'slate-react/dist/slate-react' {
  declare module.exports: any;
}

declare module 'slate-react/dist/slate-react.min' {
  declare module.exports: any;
}

declare module 'slate-react/lib/components/content' {
  declare module.exports: any;
}

declare module 'slate-react/lib/components/editor' {
  declare module.exports: any;
}

declare module 'slate-react/lib/components/leaf' {
  declare module.exports: any;
}

declare module 'slate-react/lib/components/node' {
  declare module.exports: any;
}

declare module 'slate-react/lib/components/placeholder' {
  declare module.exports: any;
}

declare module 'slate-react/lib/components/text' {
  declare module.exports: any;
}

declare module 'slate-react/lib/components/void' {
  declare module.exports: any;
}

declare module 'slate-react/lib/constants/environment' {
  declare module.exports: any;
}

declare module 'slate-react/lib/constants/transfer-types' {
  declare module.exports: any;
}

declare module 'slate-react/lib/index' {
  declare module.exports: any;
}

declare module 'slate-react/lib/plugins/after' {
  declare module.exports: any;
}

declare module 'slate-react/lib/plugins/before' {
  declare module.exports: any;
}

declare module 'slate-react/lib/plugins/core' {
  declare module.exports: any;
}

declare module 'slate-react/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/extend-selection' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/find-closest-node' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/find-deepest-node' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/find-dom-node' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/get-caret-position' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/get-html-from-native-paste' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/get-point' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/get-transfer-data' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/noop' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/normalize-node-and-offset' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/offset-key' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/scroll-to-selection' {
  declare module.exports: any;
}

declare module 'slate-react/lib/utils/set-transfer-data' {
  declare module.exports: any;
}

// Filename aliases
declare module 'slate-react/dist/slate-react.js' {
  declare module.exports: $Exports<'slate-react/dist/slate-react'>;
}
declare module 'slate-react/dist/slate-react.min.js' {
  declare module.exports: $Exports<'slate-react/dist/slate-react.min'>;
}
declare module 'slate-react/lib/components/content.js' {
  declare module.exports: $Exports<'slate-react/lib/components/content'>;
}
declare module 'slate-react/lib/components/editor.js' {
  declare module.exports: $Exports<'slate-react/lib/components/editor'>;
}
declare module 'slate-react/lib/components/leaf.js' {
  declare module.exports: $Exports<'slate-react/lib/components/leaf'>;
}
declare module 'slate-react/lib/components/node.js' {
  declare module.exports: $Exports<'slate-react/lib/components/node'>;
}
declare module 'slate-react/lib/components/placeholder.js' {
  declare module.exports: $Exports<'slate-react/lib/components/placeholder'>;
}
declare module 'slate-react/lib/components/text.js' {
  declare module.exports: $Exports<'slate-react/lib/components/text'>;
}
declare module 'slate-react/lib/components/void.js' {
  declare module.exports: $Exports<'slate-react/lib/components/void'>;
}
declare module 'slate-react/lib/constants/environment.js' {
  declare module.exports: $Exports<'slate-react/lib/constants/environment'>;
}
declare module 'slate-react/lib/constants/transfer-types.js' {
  declare module.exports: $Exports<'slate-react/lib/constants/transfer-types'>;
}
declare module 'slate-react/lib/index.js' {
  declare module.exports: $Exports<'slate-react/lib/index'>;
}
declare module 'slate-react/lib/plugins/after.js' {
  declare module.exports: $Exports<'slate-react/lib/plugins/after'>;
}
declare module 'slate-react/lib/plugins/before.js' {
  declare module.exports: $Exports<'slate-react/lib/plugins/before'>;
}
declare module 'slate-react/lib/plugins/core.js' {
  declare module.exports: $Exports<'slate-react/lib/plugins/core'>;
}
declare module 'slate-react/lib/plugins/index.js' {
  declare module.exports: $Exports<'slate-react/lib/plugins/index'>;
}
declare module 'slate-react/lib/utils/extend-selection.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/extend-selection'>;
}
declare module 'slate-react/lib/utils/find-closest-node.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/find-closest-node'>;
}
declare module 'slate-react/lib/utils/find-deepest-node.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/find-deepest-node'>;
}
declare module 'slate-react/lib/utils/find-dom-node.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/find-dom-node'>;
}
declare module 'slate-react/lib/utils/get-caret-position.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/get-caret-position'>;
}
declare module 'slate-react/lib/utils/get-html-from-native-paste.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/get-html-from-native-paste'>;
}
declare module 'slate-react/lib/utils/get-point.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/get-point'>;
}
declare module 'slate-react/lib/utils/get-transfer-data.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/get-transfer-data'>;
}
declare module 'slate-react/lib/utils/noop.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/noop'>;
}
declare module 'slate-react/lib/utils/normalize-node-and-offset.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/normalize-node-and-offset'>;
}
declare module 'slate-react/lib/utils/offset-key.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/offset-key'>;
}
declare module 'slate-react/lib/utils/scroll-to-selection.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/scroll-to-selection'>;
}
declare module 'slate-react/lib/utils/set-transfer-data.js' {
  declare module.exports: $Exports<'slate-react/lib/utils/set-transfer-data'>;
}
