// flow-typed signature: c66ad9edadefdf0ebb97c1106243038b
// flow-typed version: <<STUB>>/start-server-webpack-plugin_v^2.2.5/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'start-server-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'start-server-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'start-server-webpack-plugin/dist/StartServerPlugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'start-server-webpack-plugin/dist/StartServerPlugin.js' {
  declare module.exports: $Exports<'start-server-webpack-plugin/dist/StartServerPlugin'>;
}
