// flow-typed signature: 6aff554763123f8abe30dfd08096c353
// flow-typed version: <<STUB>>/webpack-filter-warnings-plugin_v^1.2.1/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-filter-warnings-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-filter-warnings-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-filter-warnings-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'webpack-filter-warnings-plugin/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-filter-warnings-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'webpack-filter-warnings-plugin/dist/cjs'>;
}
declare module 'webpack-filter-warnings-plugin/dist/index.js' {
  declare module.exports: $Exports<'webpack-filter-warnings-plugin/dist/index'>;
}
