// flow-typed signature: 1f4ff2fb771dc744f72b892549e9f3f6
// flow-typed version: <<STUB>>/websocket.js_v^0.1.7/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'websocket.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'websocket.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'websocket.js/dist/websocket' {
  declare module.exports: any;
}

declare module 'websocket.js/dist/websocket.min' {
  declare module.exports: any;
}

declare module 'websocket.js/lib/index' {
  declare module.exports: any;
}

declare module 'websocket.js/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'websocket.js/dist/websocket.js' {
  declare module.exports: $Exports<'websocket.js/dist/websocket'>;
}
declare module 'websocket.js/dist/websocket.min.js' {
  declare module.exports: $Exports<'websocket.js/dist/websocket.min'>;
}
declare module 'websocket.js/lib/index.js' {
  declare module.exports: $Exports<'websocket.js/lib/index'>;
}
declare module 'websocket.js/src/index.js' {
  declare module.exports: $Exports<'websocket.js/src/index'>;
}
