// flow-typed signature: c7af573e81362c7a80470d4659a1431f
// flow-typed version: <<STUB>>/@webkom/lego-editor_v^1.2.1/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webkom/lego-editor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webkom/lego-editor' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webkom/lego-editor/dist/components/FigcaptionBlock' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/components/ImageBlock' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/components/ImageUpload' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/components/Toolbar' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/example/webpack/webpack.config' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/plugins/editList' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/plugins/images' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/plugins' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/plugins/markdown' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/plugins/pasteLink' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/serializer' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/dist/utils/cropImage' {
  declare module.exports: any;
}

declare module '@webkom/lego-editor/example/webpack/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webkom/lego-editor/dist/components/FigcaptionBlock.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/components/FigcaptionBlock'>;
}
declare module '@webkom/lego-editor/dist/components/ImageBlock.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/components/ImageBlock'>;
}
declare module '@webkom/lego-editor/dist/components/ImageUpload.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/components/ImageUpload'>;
}
declare module '@webkom/lego-editor/dist/components/Toolbar.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/components/Toolbar'>;
}
declare module '@webkom/lego-editor/dist/example/webpack/webpack.config.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/example/webpack/webpack.config'>;
}
declare module '@webkom/lego-editor/dist/index' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist'>;
}
declare module '@webkom/lego-editor/dist/index.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist'>;
}
declare module '@webkom/lego-editor/dist/plugins/editList.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/plugins/editList'>;
}
declare module '@webkom/lego-editor/dist/plugins/images.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/plugins/images'>;
}
declare module '@webkom/lego-editor/dist/plugins/index' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/plugins'>;
}
declare module '@webkom/lego-editor/dist/plugins/index.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/plugins'>;
}
declare module '@webkom/lego-editor/dist/plugins/markdown.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/plugins/markdown'>;
}
declare module '@webkom/lego-editor/dist/plugins/pasteLink.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/plugins/pasteLink'>;
}
declare module '@webkom/lego-editor/dist/serializer.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/serializer'>;
}
declare module '@webkom/lego-editor/dist/utils/cropImage.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/dist/utils/cropImage'>;
}
declare module '@webkom/lego-editor/example/webpack/webpack.config.js' {
  declare module.exports: $Exports<'@webkom/lego-editor/example/webpack/webpack.config'>;
}
