// flow-typed signature: 12ab4c83e3b24e6ef550ccfe74ede5fe
// flow-typed version: <<STUB>>/@webkom/react-meter-bar_v^1.0.3/flow_v0.137.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webkom/react-meter-bar'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webkom/react-meter-bar' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webkom/react-meter-bar/dist' {
  declare module.exports: any;
}

declare module '@webkom/react-meter-bar/example/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webkom/react-meter-bar/dist/index' {
  declare module.exports: $Exports<'@webkom/react-meter-bar/dist'>;
}
declare module '@webkom/react-meter-bar/dist/index.js' {
  declare module.exports: $Exports<'@webkom/react-meter-bar/dist'>;
}
declare module '@webkom/react-meter-bar/example/dist/main.js' {
  declare module.exports: $Exports<'@webkom/react-meter-bar/example/dist/main'>;
}
